// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devjournal/v1/journal.proto

package devjournalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "devjournal/proto/devjournal/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JournalServiceName is the fully-qualified name of the JournalService service.
	JournalServiceName = "devjournal.v1.JournalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JournalServiceCreateEntryProcedure is the fully-qualified name of the JournalService's
	// CreateEntry RPC.
	JournalServiceCreateEntryProcedure = "/devjournal.v1.JournalService/CreateEntry"
	// JournalServiceGetEntryProcedure is the fully-qualified name of the JournalService's GetEntry RPC.
	JournalServiceGetEntryProcedure = "/devjournal.v1.JournalService/GetEntry"
	// JournalServiceListEntriesProcedure is the fully-qualified name of the JournalService's
	// ListEntries RPC.
	JournalServiceListEntriesProcedure = "/devjournal.v1.JournalService/ListEntries"
	// JournalServiceUpdateEntryProcedure is the fully-qualified name of the JournalService's
	// UpdateEntry RPC.
	JournalServiceUpdateEntryProcedure = "/devjournal.v1.JournalService/UpdateEntry"
	// JournalServiceDeleteEntryProcedure is the fully-qualified name of the JournalService's
	// DeleteEntry RPC.
	JournalServiceDeleteEntryProcedure = "/devjournal.v1.JournalService/DeleteEntry"
	// JournalServiceSearchEntriesProcedure is the fully-qualified name of the JournalService's
	// SearchEntries RPC.
	JournalServiceSearchEntriesProcedure = "/devjournal.v1.JournalService/SearchEntries"
)

// JournalServiceClient is a client for the devjournal.v1.JournalService service.
type JournalServiceClient interface {
	// CreateEntry creates a new journal entry
	CreateEntry(context.Context, *connect.Request[v1.CreateEntryRequest]) (*connect.Response[v1.JournalEntry], error)
	// GetEntry retrieves a single journal entry by ID
	GetEntry(context.Context, *connect.Request[v1.GetEntryRequest]) (*connect.Response[v1.JournalEntry], error)
	// ListEntries retrieves a paginated list of journal entries
	ListEntries(context.Context, *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error)
	// UpdateEntry updates an existing journal entry
	UpdateEntry(context.Context, *connect.Request[v1.UpdateEntryRequest]) (*connect.Response[v1.JournalEntry], error)
	// DeleteEntry removes a journal entry
	DeleteEntry(context.Context, *connect.Request[v1.DeleteEntryRequest]) (*connect.Response[v1.DeleteEntryResponse], error)
	// SearchEntries searches journal entries by title or content
	SearchEntries(context.Context, *connect.Request[v1.SearchEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error)
}

// NewJournalServiceClient constructs a client for the devjournal.v1.JournalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJournalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JournalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	journalServiceMethods := v1.File_devjournal_v1_journal_proto.Services().ByName("JournalService").Methods()
	return &journalServiceClient{
		createEntry: connect.NewClient[v1.CreateEntryRequest, v1.JournalEntry](
			httpClient,
			baseURL+JournalServiceCreateEntryProcedure,
			connect.WithSchema(journalServiceMethods.ByName("CreateEntry")),
			connect.WithClientOptions(opts...),
		),
		getEntry: connect.NewClient[v1.GetEntryRequest, v1.JournalEntry](
			httpClient,
			baseURL+JournalServiceGetEntryProcedure,
			connect.WithSchema(journalServiceMethods.ByName("GetEntry")),
			connect.WithClientOptions(opts...),
		),
		listEntries: connect.NewClient[v1.ListEntriesRequest, v1.ListEntriesResponse](
			httpClient,
			baseURL+JournalServiceListEntriesProcedure,
			connect.WithSchema(journalServiceMethods.ByName("ListEntries")),
			connect.WithClientOptions(opts...),
		),
		updateEntry: connect.NewClient[v1.UpdateEntryRequest, v1.JournalEntry](
			httpClient,
			baseURL+JournalServiceUpdateEntryProcedure,
			connect.WithSchema(journalServiceMethods.ByName("UpdateEntry")),
			connect.WithClientOptions(opts...),
		),
		deleteEntry: connect.NewClient[v1.DeleteEntryRequest, v1.DeleteEntryResponse](
			httpClient,
			baseURL+JournalServiceDeleteEntryProcedure,
			connect.WithSchema(journalServiceMethods.ByName("DeleteEntry")),
			connect.WithClientOptions(opts...),
		),
		searchEntries: connect.NewClient[v1.SearchEntriesRequest, v1.ListEntriesResponse](
			httpClient,
			baseURL+JournalServiceSearchEntriesProcedure,
			connect.WithSchema(journalServiceMethods.ByName("SearchEntries")),
			connect.WithClientOptions(opts...),
		),
	}
}

// journalServiceClient implements JournalServiceClient.
type journalServiceClient struct {
	createEntry   *connect.Client[v1.CreateEntryRequest, v1.JournalEntry]
	getEntry      *connect.Client[v1.GetEntryRequest, v1.JournalEntry]
	listEntries   *connect.Client[v1.ListEntriesRequest, v1.ListEntriesResponse]
	updateEntry   *connect.Client[v1.UpdateEntryRequest, v1.JournalEntry]
	deleteEntry   *connect.Client[v1.DeleteEntryRequest, v1.DeleteEntryResponse]
	searchEntries *connect.Client[v1.SearchEntriesRequest, v1.ListEntriesResponse]
}

// CreateEntry calls devjournal.v1.JournalService.CreateEntry.
func (c *journalServiceClient) CreateEntry(ctx context.Context, req *connect.Request[v1.CreateEntryRequest]) (*connect.Response[v1.JournalEntry], error) {
	return c.createEntry.CallUnary(ctx, req)
}

// GetEntry calls devjournal.v1.JournalService.GetEntry.
func (c *journalServiceClient) GetEntry(ctx context.Context, req *connect.Request[v1.GetEntryRequest]) (*connect.Response[v1.JournalEntry], error) {
	return c.getEntry.CallUnary(ctx, req)
}

// ListEntries calls devjournal.v1.JournalService.ListEntries.
func (c *journalServiceClient) ListEntries(ctx context.Context, req *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error) {
	return c.listEntries.CallUnary(ctx, req)
}

// UpdateEntry calls devjournal.v1.JournalService.UpdateEntry.
func (c *journalServiceClient) UpdateEntry(ctx context.Context, req *connect.Request[v1.UpdateEntryRequest]) (*connect.Response[v1.JournalEntry], error) {
	return c.updateEntry.CallUnary(ctx, req)
}

// DeleteEntry calls devjournal.v1.JournalService.DeleteEntry.
func (c *journalServiceClient) DeleteEntry(ctx context.Context, req *connect.Request[v1.DeleteEntryRequest]) (*connect.Response[v1.DeleteEntryResponse], error) {
	return c.deleteEntry.CallUnary(ctx, req)
}

// SearchEntries calls devjournal.v1.JournalService.SearchEntries.
func (c *journalServiceClient) SearchEntries(ctx context.Context, req *connect.Request[v1.SearchEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error) {
	return c.searchEntries.CallUnary(ctx, req)
}

// JournalServiceHandler is an implementation of the devjournal.v1.JournalService service.
type JournalServiceHandler interface {
	// CreateEntry creates a new journal entry
	CreateEntry(context.Context, *connect.Request[v1.CreateEntryRequest]) (*connect.Response[v1.JournalEntry], error)
	// GetEntry retrieves a single journal entry by ID
	GetEntry(context.Context, *connect.Request[v1.GetEntryRequest]) (*connect.Response[v1.JournalEntry], error)
	// ListEntries retrieves a paginated list of journal entries
	ListEntries(context.Context, *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error)
	// UpdateEntry updates an existing journal entry
	UpdateEntry(context.Context, *connect.Request[v1.UpdateEntryRequest]) (*connect.Response[v1.JournalEntry], error)
	// DeleteEntry removes a journal entry
	DeleteEntry(context.Context, *connect.Request[v1.DeleteEntryRequest]) (*connect.Response[v1.DeleteEntryResponse], error)
	// SearchEntries searches journal entries by title or content
	SearchEntries(context.Context, *connect.Request[v1.SearchEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error)
}

// NewJournalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJournalServiceHandler(svc JournalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	journalServiceMethods := v1.File_devjournal_v1_journal_proto.Services().ByName("JournalService").Methods()
	journalServiceCreateEntryHandler := connect.NewUnaryHandler(
		JournalServiceCreateEntryProcedure,
		svc.CreateEntry,
		connect.WithSchema(journalServiceMethods.ByName("CreateEntry")),
		connect.WithHandlerOptions(opts...),
	)
	journalServiceGetEntryHandler := connect.NewUnaryHandler(
		JournalServiceGetEntryProcedure,
		svc.GetEntry,
		connect.WithSchema(journalServiceMethods.ByName("GetEntry")),
		connect.WithHandlerOptions(opts...),
	)
	journalServiceListEntriesHandler := connect.NewUnaryHandler(
		JournalServiceListEntriesProcedure,
		svc.ListEntries,
		connect.WithSchema(journalServiceMethods.ByName("ListEntries")),
		connect.WithHandlerOptions(opts...),
	)
	journalServiceUpdateEntryHandler := connect.NewUnaryHandler(
		JournalServiceUpdateEntryProcedure,
		svc.UpdateEntry,
		connect.WithSchema(journalServiceMethods.ByName("UpdateEntry")),
		connect.WithHandlerOptions(opts...),
	)
	journalServiceDeleteEntryHandler := connect.NewUnaryHandler(
		JournalServiceDeleteEntryProcedure,
		svc.DeleteEntry,
		connect.WithSchema(journalServiceMethods.ByName("DeleteEntry")),
		connect.WithHandlerOptions(opts...),
	)
	journalServiceSearchEntriesHandler := connect.NewUnaryHandler(
		JournalServiceSearchEntriesProcedure,
		svc.SearchEntries,
		connect.WithSchema(journalServiceMethods.ByName("SearchEntries")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devjournal.v1.JournalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JournalServiceCreateEntryProcedure:
			journalServiceCreateEntryHandler.ServeHTTP(w, r)
		case JournalServiceGetEntryProcedure:
			journalServiceGetEntryHandler.ServeHTTP(w, r)
		case JournalServiceListEntriesProcedure:
			journalServiceListEntriesHandler.ServeHTTP(w, r)
		case JournalServiceUpdateEntryProcedure:
			journalServiceUpdateEntryHandler.ServeHTTP(w, r)
		case JournalServiceDeleteEntryProcedure:
			journalServiceDeleteEntryHandler.ServeHTTP(w, r)
		case JournalServiceSearchEntriesProcedure:
			journalServiceSearchEntriesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJournalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJournalServiceHandler struct{}

func (UnimplementedJournalServiceHandler) CreateEntry(context.Context, *connect.Request[v1.CreateEntryRequest]) (*connect.Response[v1.JournalEntry], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.JournalService.CreateEntry is not implemented"))
}

func (UnimplementedJournalServiceHandler) GetEntry(context.Context, *connect.Request[v1.GetEntryRequest]) (*connect.Response[v1.JournalEntry], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.JournalService.GetEntry is not implemented"))
}

func (UnimplementedJournalServiceHandler) ListEntries(context.Context, *connect.Request[v1.ListEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.JournalService.ListEntries is not implemented"))
}

func (UnimplementedJournalServiceHandler) UpdateEntry(context.Context, *connect.Request[v1.UpdateEntryRequest]) (*connect.Response[v1.JournalEntry], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.JournalService.UpdateEntry is not implemented"))
}

func (UnimplementedJournalServiceHandler) DeleteEntry(context.Context, *connect.Request[v1.DeleteEntryRequest]) (*connect.Response[v1.DeleteEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.JournalService.DeleteEntry is not implemented"))
}

func (UnimplementedJournalServiceHandler) SearchEntries(context.Context, *connect.Request[v1.SearchEntriesRequest]) (*connect.Response[v1.ListEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.JournalService.SearchEntries is not implemented"))
}
