// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devjournal/v1/progress.proto

package devjournalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "devjournal/proto/devjournal/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProgressServiceName is the fully-qualified name of the ProgressService service.
	ProgressServiceName = "devjournal.v1.ProgressService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProgressServiceGetSummaryProcedure is the fully-qualified name of the ProgressService's
	// GetSummary RPC.
	ProgressServiceGetSummaryProcedure = "/devjournal.v1.ProgressService/GetSummary"
	// ProgressServiceGetTodayProgressProcedure is the fully-qualified name of the ProgressService's
	// GetTodayProgress RPC.
	ProgressServiceGetTodayProgressProcedure = "/devjournal.v1.ProgressService/GetTodayProgress"
	// ProgressServiceGetWeeklyProgressProcedure is the fully-qualified name of the ProgressService's
	// GetWeeklyProgress RPC.
	ProgressServiceGetWeeklyProgressProcedure = "/devjournal.v1.ProgressService/GetWeeklyProgress"
	// ProgressServiceGetMonthlyProgressProcedure is the fully-qualified name of the ProgressService's
	// GetMonthlyProgress RPC.
	ProgressServiceGetMonthlyProgressProcedure = "/devjournal.v1.ProgressService/GetMonthlyProgress"
	// ProgressServiceGetStreakProcedure is the fully-qualified name of the ProgressService's GetStreak
	// RPC.
	ProgressServiceGetStreakProcedure = "/devjournal.v1.ProgressService/GetStreak"
)

// ProgressServiceClient is a client for the devjournal.v1.ProgressService service.
type ProgressServiceClient interface {
	// GetSummary retrieves the overall progress summary
	GetSummary(context.Context, *connect.Request[v1.GetSummaryRequest]) (*connect.Response[v1.ProgressSummary], error)
	// GetTodayProgress retrieves today's progress
	GetTodayProgress(context.Context, *connect.Request[v1.GetTodayProgressRequest]) (*connect.Response[v1.DailyProgress], error)
	// GetWeeklyProgress retrieves the last 7 days of progress
	GetWeeklyProgress(context.Context, *connect.Request[v1.GetWeeklyProgressRequest]) (*connect.Response[v1.ProgressList], error)
	// GetMonthlyProgress retrieves the last 30 days of progress
	GetMonthlyProgress(context.Context, *connect.Request[v1.GetMonthlyProgressRequest]) (*connect.Response[v1.ProgressList], error)
	// GetStreak retrieves the current learning streak
	GetStreak(context.Context, *connect.Request[v1.GetStreakRequest]) (*connect.Response[v1.StreakResponse], error)
}

// NewProgressServiceClient constructs a client for the devjournal.v1.ProgressService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProgressServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProgressServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	progressServiceMethods := v1.File_devjournal_v1_progress_proto.Services().ByName("ProgressService").Methods()
	return &progressServiceClient{
		getSummary: connect.NewClient[v1.GetSummaryRequest, v1.ProgressSummary](
			httpClient,
			baseURL+ProgressServiceGetSummaryProcedure,
			connect.WithSchema(progressServiceMethods.ByName("GetSummary")),
			connect.WithClientOptions(opts...),
		),
		getTodayProgress: connect.NewClient[v1.GetTodayProgressRequest, v1.DailyProgress](
			httpClient,
			baseURL+ProgressServiceGetTodayProgressProcedure,
			connect.WithSchema(progressServiceMethods.ByName("GetTodayProgress")),
			connect.WithClientOptions(opts...),
		),
		getWeeklyProgress: connect.NewClient[v1.GetWeeklyProgressRequest, v1.ProgressList](
			httpClient,
			baseURL+ProgressServiceGetWeeklyProgressProcedure,
			connect.WithSchema(progressServiceMethods.ByName("GetWeeklyProgress")),
			connect.WithClientOptions(opts...),
		),
		getMonthlyProgress: connect.NewClient[v1.GetMonthlyProgressRequest, v1.ProgressList](
			httpClient,
			baseURL+ProgressServiceGetMonthlyProgressProcedure,
			connect.WithSchema(progressServiceMethods.ByName("GetMonthlyProgress")),
			connect.WithClientOptions(opts...),
		),
		getStreak: connect.NewClient[v1.GetStreakRequest, v1.StreakResponse](
			httpClient,
			baseURL+ProgressServiceGetStreakProcedure,
			connect.WithSchema(progressServiceMethods.ByName("GetStreak")),
			connect.WithClientOptions(opts...),
		),
	}
}

// progressServiceClient implements ProgressServiceClient.
type progressServiceClient struct {
	getSummary         *connect.Client[v1.GetSummaryRequest, v1.ProgressSummary]
	getTodayProgress   *connect.Client[v1.GetTodayProgressRequest, v1.DailyProgress]
	getWeeklyProgress  *connect.Client[v1.GetWeeklyProgressRequest, v1.ProgressList]
	getMonthlyProgress *connect.Client[v1.GetMonthlyProgressRequest, v1.ProgressList]
	getStreak          *connect.Client[v1.GetStreakRequest, v1.StreakResponse]
}

// GetSummary calls devjournal.v1.ProgressService.GetSummary.
func (c *progressServiceClient) GetSummary(ctx context.Context, req *connect.Request[v1.GetSummaryRequest]) (*connect.Response[v1.ProgressSummary], error) {
	return c.getSummary.CallUnary(ctx, req)
}

// GetTodayProgress calls devjournal.v1.ProgressService.GetTodayProgress.
func (c *progressServiceClient) GetTodayProgress(ctx context.Context, req *connect.Request[v1.GetTodayProgressRequest]) (*connect.Response[v1.DailyProgress], error) {
	return c.getTodayProgress.CallUnary(ctx, req)
}

// GetWeeklyProgress calls devjournal.v1.ProgressService.GetWeeklyProgress.
func (c *progressServiceClient) GetWeeklyProgress(ctx context.Context, req *connect.Request[v1.GetWeeklyProgressRequest]) (*connect.Response[v1.ProgressList], error) {
	return c.getWeeklyProgress.CallUnary(ctx, req)
}

// GetMonthlyProgress calls devjournal.v1.ProgressService.GetMonthlyProgress.
func (c *progressServiceClient) GetMonthlyProgress(ctx context.Context, req *connect.Request[v1.GetMonthlyProgressRequest]) (*connect.Response[v1.ProgressList], error) {
	return c.getMonthlyProgress.CallUnary(ctx, req)
}

// GetStreak calls devjournal.v1.ProgressService.GetStreak.
func (c *progressServiceClient) GetStreak(ctx context.Context, req *connect.Request[v1.GetStreakRequest]) (*connect.Response[v1.StreakResponse], error) {
	return c.getStreak.CallUnary(ctx, req)
}

// ProgressServiceHandler is an implementation of the devjournal.v1.ProgressService service.
type ProgressServiceHandler interface {
	// GetSummary retrieves the overall progress summary
	GetSummary(context.Context, *connect.Request[v1.GetSummaryRequest]) (*connect.Response[v1.ProgressSummary], error)
	// GetTodayProgress retrieves today's progress
	GetTodayProgress(context.Context, *connect.Request[v1.GetTodayProgressRequest]) (*connect.Response[v1.DailyProgress], error)
	// GetWeeklyProgress retrieves the last 7 days of progress
	GetWeeklyProgress(context.Context, *connect.Request[v1.GetWeeklyProgressRequest]) (*connect.Response[v1.ProgressList], error)
	// GetMonthlyProgress retrieves the last 30 days of progress
	GetMonthlyProgress(context.Context, *connect.Request[v1.GetMonthlyProgressRequest]) (*connect.Response[v1.ProgressList], error)
	// GetStreak retrieves the current learning streak
	GetStreak(context.Context, *connect.Request[v1.GetStreakRequest]) (*connect.Response[v1.StreakResponse], error)
}

// NewProgressServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProgressServiceHandler(svc ProgressServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	progressServiceMethods := v1.File_devjournal_v1_progress_proto.Services().ByName("ProgressService").Methods()
	progressServiceGetSummaryHandler := connect.NewUnaryHandler(
		ProgressServiceGetSummaryProcedure,
		svc.GetSummary,
		connect.WithSchema(progressServiceMethods.ByName("GetSummary")),
		connect.WithHandlerOptions(opts...),
	)
	progressServiceGetTodayProgressHandler := connect.NewUnaryHandler(
		ProgressServiceGetTodayProgressProcedure,
		svc.GetTodayProgress,
		connect.WithSchema(progressServiceMethods.ByName("GetTodayProgress")),
		connect.WithHandlerOptions(opts...),
	)
	progressServiceGetWeeklyProgressHandler := connect.NewUnaryHandler(
		ProgressServiceGetWeeklyProgressProcedure,
		svc.GetWeeklyProgress,
		connect.WithSchema(progressServiceMethods.ByName("GetWeeklyProgress")),
		connect.WithHandlerOptions(opts...),
	)
	progressServiceGetMonthlyProgressHandler := connect.NewUnaryHandler(
		ProgressServiceGetMonthlyProgressProcedure,
		svc.GetMonthlyProgress,
		connect.WithSchema(progressServiceMethods.ByName("GetMonthlyProgress")),
		connect.WithHandlerOptions(opts...),
	)
	progressServiceGetStreakHandler := connect.NewUnaryHandler(
		ProgressServiceGetStreakProcedure,
		svc.GetStreak,
		connect.WithSchema(progressServiceMethods.ByName("GetStreak")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devjournal.v1.ProgressService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProgressServiceGetSummaryProcedure:
			progressServiceGetSummaryHandler.ServeHTTP(w, r)
		case ProgressServiceGetTodayProgressProcedure:
			progressServiceGetTodayProgressHandler.ServeHTTP(w, r)
		case ProgressServiceGetWeeklyProgressProcedure:
			progressServiceGetWeeklyProgressHandler.ServeHTTP(w, r)
		case ProgressServiceGetMonthlyProgressProcedure:
			progressServiceGetMonthlyProgressHandler.ServeHTTP(w, r)
		case ProgressServiceGetStreakProcedure:
			progressServiceGetStreakHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProgressServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProgressServiceHandler struct{}

func (UnimplementedProgressServiceHandler) GetSummary(context.Context, *connect.Request[v1.GetSummaryRequest]) (*connect.Response[v1.ProgressSummary], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.ProgressService.GetSummary is not implemented"))
}

func (UnimplementedProgressServiceHandler) GetTodayProgress(context.Context, *connect.Request[v1.GetTodayProgressRequest]) (*connect.Response[v1.DailyProgress], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.ProgressService.GetTodayProgress is not implemented"))
}

func (UnimplementedProgressServiceHandler) GetWeeklyProgress(context.Context, *connect.Request[v1.GetWeeklyProgressRequest]) (*connect.Response[v1.ProgressList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.ProgressService.GetWeeklyProgress is not implemented"))
}

func (UnimplementedProgressServiceHandler) GetMonthlyProgress(context.Context, *connect.Request[v1.GetMonthlyProgressRequest]) (*connect.Response[v1.ProgressList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.ProgressService.GetMonthlyProgress is not implemented"))
}

func (UnimplementedProgressServiceHandler) GetStreak(context.Context, *connect.Request[v1.GetStreakRequest]) (*connect.Response[v1.StreakResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.ProgressService.GetStreak is not implemented"))
}
