// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devjournal/v1/snippet.proto

package devjournalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "devjournal/proto/devjournal/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SnippetServiceName is the fully-qualified name of the SnippetService service.
	SnippetServiceName = "devjournal.v1.SnippetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SnippetServiceCreateSnippetProcedure is the fully-qualified name of the SnippetService's
	// CreateSnippet RPC.
	SnippetServiceCreateSnippetProcedure = "/devjournal.v1.SnippetService/CreateSnippet"
	// SnippetServiceGetSnippetProcedure is the fully-qualified name of the SnippetService's GetSnippet
	// RPC.
	SnippetServiceGetSnippetProcedure = "/devjournal.v1.SnippetService/GetSnippet"
	// SnippetServiceListSnippetsProcedure is the fully-qualified name of the SnippetService's
	// ListSnippets RPC.
	SnippetServiceListSnippetsProcedure = "/devjournal.v1.SnippetService/ListSnippets"
	// SnippetServiceUpdateSnippetProcedure is the fully-qualified name of the SnippetService's
	// UpdateSnippet RPC.
	SnippetServiceUpdateSnippetProcedure = "/devjournal.v1.SnippetService/UpdateSnippet"
	// SnippetServiceDeleteSnippetProcedure is the fully-qualified name of the SnippetService's
	// DeleteSnippet RPC.
	SnippetServiceDeleteSnippetProcedure = "/devjournal.v1.SnippetService/DeleteSnippet"
	// SnippetServiceSearchSnippetsProcedure is the fully-qualified name of the SnippetService's
	// SearchSnippets RPC.
	SnippetServiceSearchSnippetsProcedure = "/devjournal.v1.SnippetService/SearchSnippets"
	// SnippetServiceGetLanguageStatsProcedure is the fully-qualified name of the SnippetService's
	// GetLanguageStats RPC.
	SnippetServiceGetLanguageStatsProcedure = "/devjournal.v1.SnippetService/GetLanguageStats"
)

// SnippetServiceClient is a client for the devjournal.v1.SnippetService service.
type SnippetServiceClient interface {
	// CreateSnippet creates a new code snippet
	CreateSnippet(context.Context, *connect.Request[v1.CreateSnippetRequest]) (*connect.Response[v1.Snippet], error)
	// GetSnippet retrieves a single snippet by ID
	GetSnippet(context.Context, *connect.Request[v1.GetSnippetRequest]) (*connect.Response[v1.Snippet], error)
	// ListSnippets retrieves a paginated list of snippets
	ListSnippets(context.Context, *connect.Request[v1.ListSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error)
	// UpdateSnippet updates an existing snippet
	UpdateSnippet(context.Context, *connect.Request[v1.UpdateSnippetRequest]) (*connect.Response[v1.Snippet], error)
	// DeleteSnippet removes a snippet
	DeleteSnippet(context.Context, *connect.Request[v1.DeleteSnippetRequest]) (*connect.Response[v1.DeleteSnippetResponse], error)
	// SearchSnippets performs full-text search on snippets
	SearchSnippets(context.Context, *connect.Request[v1.SearchSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error)
	// GetLanguageStats returns snippet counts grouped by language
	GetLanguageStats(context.Context, *connect.Request[v1.GetLanguageStatsRequest]) (*connect.Response[v1.GetLanguageStatsResponse], error)
}

// NewSnippetServiceClient constructs a client for the devjournal.v1.SnippetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSnippetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SnippetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	snippetServiceMethods := v1.File_devjournal_v1_snippet_proto.Services().ByName("SnippetService").Methods()
	return &snippetServiceClient{
		createSnippet: connect.NewClient[v1.CreateSnippetRequest, v1.Snippet](
			httpClient,
			baseURL+SnippetServiceCreateSnippetProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("CreateSnippet")),
			connect.WithClientOptions(opts...),
		),
		getSnippet: connect.NewClient[v1.GetSnippetRequest, v1.Snippet](
			httpClient,
			baseURL+SnippetServiceGetSnippetProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("GetSnippet")),
			connect.WithClientOptions(opts...),
		),
		listSnippets: connect.NewClient[v1.ListSnippetsRequest, v1.ListSnippetsResponse](
			httpClient,
			baseURL+SnippetServiceListSnippetsProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("ListSnippets")),
			connect.WithClientOptions(opts...),
		),
		updateSnippet: connect.NewClient[v1.UpdateSnippetRequest, v1.Snippet](
			httpClient,
			baseURL+SnippetServiceUpdateSnippetProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("UpdateSnippet")),
			connect.WithClientOptions(opts...),
		),
		deleteSnippet: connect.NewClient[v1.DeleteSnippetRequest, v1.DeleteSnippetResponse](
			httpClient,
			baseURL+SnippetServiceDeleteSnippetProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("DeleteSnippet")),
			connect.WithClientOptions(opts...),
		),
		searchSnippets: connect.NewClient[v1.SearchSnippetsRequest, v1.ListSnippetsResponse](
			httpClient,
			baseURL+SnippetServiceSearchSnippetsProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("SearchSnippets")),
			connect.WithClientOptions(opts...),
		),
		getLanguageStats: connect.NewClient[v1.GetLanguageStatsRequest, v1.GetLanguageStatsResponse](
			httpClient,
			baseURL+SnippetServiceGetLanguageStatsProcedure,
			connect.WithSchema(snippetServiceMethods.ByName("GetLanguageStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// snippetServiceClient implements SnippetServiceClient.
type snippetServiceClient struct {
	createSnippet    *connect.Client[v1.CreateSnippetRequest, v1.Snippet]
	getSnippet       *connect.Client[v1.GetSnippetRequest, v1.Snippet]
	listSnippets     *connect.Client[v1.ListSnippetsRequest, v1.ListSnippetsResponse]
	updateSnippet    *connect.Client[v1.UpdateSnippetRequest, v1.Snippet]
	deleteSnippet    *connect.Client[v1.DeleteSnippetRequest, v1.DeleteSnippetResponse]
	searchSnippets   *connect.Client[v1.SearchSnippetsRequest, v1.ListSnippetsResponse]
	getLanguageStats *connect.Client[v1.GetLanguageStatsRequest, v1.GetLanguageStatsResponse]
}

// CreateSnippet calls devjournal.v1.SnippetService.CreateSnippet.
func (c *snippetServiceClient) CreateSnippet(ctx context.Context, req *connect.Request[v1.CreateSnippetRequest]) (*connect.Response[v1.Snippet], error) {
	return c.createSnippet.CallUnary(ctx, req)
}

// GetSnippet calls devjournal.v1.SnippetService.GetSnippet.
func (c *snippetServiceClient) GetSnippet(ctx context.Context, req *connect.Request[v1.GetSnippetRequest]) (*connect.Response[v1.Snippet], error) {
	return c.getSnippet.CallUnary(ctx, req)
}

// ListSnippets calls devjournal.v1.SnippetService.ListSnippets.
func (c *snippetServiceClient) ListSnippets(ctx context.Context, req *connect.Request[v1.ListSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error) {
	return c.listSnippets.CallUnary(ctx, req)
}

// UpdateSnippet calls devjournal.v1.SnippetService.UpdateSnippet.
func (c *snippetServiceClient) UpdateSnippet(ctx context.Context, req *connect.Request[v1.UpdateSnippetRequest]) (*connect.Response[v1.Snippet], error) {
	return c.updateSnippet.CallUnary(ctx, req)
}

// DeleteSnippet calls devjournal.v1.SnippetService.DeleteSnippet.
func (c *snippetServiceClient) DeleteSnippet(ctx context.Context, req *connect.Request[v1.DeleteSnippetRequest]) (*connect.Response[v1.DeleteSnippetResponse], error) {
	return c.deleteSnippet.CallUnary(ctx, req)
}

// SearchSnippets calls devjournal.v1.SnippetService.SearchSnippets.
func (c *snippetServiceClient) SearchSnippets(ctx context.Context, req *connect.Request[v1.SearchSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error) {
	return c.searchSnippets.CallUnary(ctx, req)
}

// GetLanguageStats calls devjournal.v1.SnippetService.GetLanguageStats.
func (c *snippetServiceClient) GetLanguageStats(ctx context.Context, req *connect.Request[v1.GetLanguageStatsRequest]) (*connect.Response[v1.GetLanguageStatsResponse], error) {
	return c.getLanguageStats.CallUnary(ctx, req)
}

// SnippetServiceHandler is an implementation of the devjournal.v1.SnippetService service.
type SnippetServiceHandler interface {
	// CreateSnippet creates a new code snippet
	CreateSnippet(context.Context, *connect.Request[v1.CreateSnippetRequest]) (*connect.Response[v1.Snippet], error)
	// GetSnippet retrieves a single snippet by ID
	GetSnippet(context.Context, *connect.Request[v1.GetSnippetRequest]) (*connect.Response[v1.Snippet], error)
	// ListSnippets retrieves a paginated list of snippets
	ListSnippets(context.Context, *connect.Request[v1.ListSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error)
	// UpdateSnippet updates an existing snippet
	UpdateSnippet(context.Context, *connect.Request[v1.UpdateSnippetRequest]) (*connect.Response[v1.Snippet], error)
	// DeleteSnippet removes a snippet
	DeleteSnippet(context.Context, *connect.Request[v1.DeleteSnippetRequest]) (*connect.Response[v1.DeleteSnippetResponse], error)
	// SearchSnippets performs full-text search on snippets
	SearchSnippets(context.Context, *connect.Request[v1.SearchSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error)
	// GetLanguageStats returns snippet counts grouped by language
	GetLanguageStats(context.Context, *connect.Request[v1.GetLanguageStatsRequest]) (*connect.Response[v1.GetLanguageStatsResponse], error)
}

// NewSnippetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSnippetServiceHandler(svc SnippetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	snippetServiceMethods := v1.File_devjournal_v1_snippet_proto.Services().ByName("SnippetService").Methods()
	snippetServiceCreateSnippetHandler := connect.NewUnaryHandler(
		SnippetServiceCreateSnippetProcedure,
		svc.CreateSnippet,
		connect.WithSchema(snippetServiceMethods.ByName("CreateSnippet")),
		connect.WithHandlerOptions(opts...),
	)
	snippetServiceGetSnippetHandler := connect.NewUnaryHandler(
		SnippetServiceGetSnippetProcedure,
		svc.GetSnippet,
		connect.WithSchema(snippetServiceMethods.ByName("GetSnippet")),
		connect.WithHandlerOptions(opts...),
	)
	snippetServiceListSnippetsHandler := connect.NewUnaryHandler(
		SnippetServiceListSnippetsProcedure,
		svc.ListSnippets,
		connect.WithSchema(snippetServiceMethods.ByName("ListSnippets")),
		connect.WithHandlerOptions(opts...),
	)
	snippetServiceUpdateSnippetHandler := connect.NewUnaryHandler(
		SnippetServiceUpdateSnippetProcedure,
		svc.UpdateSnippet,
		connect.WithSchema(snippetServiceMethods.ByName("UpdateSnippet")),
		connect.WithHandlerOptions(opts...),
	)
	snippetServiceDeleteSnippetHandler := connect.NewUnaryHandler(
		SnippetServiceDeleteSnippetProcedure,
		svc.DeleteSnippet,
		connect.WithSchema(snippetServiceMethods.ByName("DeleteSnippet")),
		connect.WithHandlerOptions(opts...),
	)
	snippetServiceSearchSnippetsHandler := connect.NewUnaryHandler(
		SnippetServiceSearchSnippetsProcedure,
		svc.SearchSnippets,
		connect.WithSchema(snippetServiceMethods.ByName("SearchSnippets")),
		connect.WithHandlerOptions(opts...),
	)
	snippetServiceGetLanguageStatsHandler := connect.NewUnaryHandler(
		SnippetServiceGetLanguageStatsProcedure,
		svc.GetLanguageStats,
		connect.WithSchema(snippetServiceMethods.ByName("GetLanguageStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devjournal.v1.SnippetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SnippetServiceCreateSnippetProcedure:
			snippetServiceCreateSnippetHandler.ServeHTTP(w, r)
		case SnippetServiceGetSnippetProcedure:
			snippetServiceGetSnippetHandler.ServeHTTP(w, r)
		case SnippetServiceListSnippetsProcedure:
			snippetServiceListSnippetsHandler.ServeHTTP(w, r)
		case SnippetServiceUpdateSnippetProcedure:
			snippetServiceUpdateSnippetHandler.ServeHTTP(w, r)
		case SnippetServiceDeleteSnippetProcedure:
			snippetServiceDeleteSnippetHandler.ServeHTTP(w, r)
		case SnippetServiceSearchSnippetsProcedure:
			snippetServiceSearchSnippetsHandler.ServeHTTP(w, r)
		case SnippetServiceGetLanguageStatsProcedure:
			snippetServiceGetLanguageStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSnippetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSnippetServiceHandler struct{}

func (UnimplementedSnippetServiceHandler) CreateSnippet(context.Context, *connect.Request[v1.CreateSnippetRequest]) (*connect.Response[v1.Snippet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.CreateSnippet is not implemented"))
}

func (UnimplementedSnippetServiceHandler) GetSnippet(context.Context, *connect.Request[v1.GetSnippetRequest]) (*connect.Response[v1.Snippet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.GetSnippet is not implemented"))
}

func (UnimplementedSnippetServiceHandler) ListSnippets(context.Context, *connect.Request[v1.ListSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.ListSnippets is not implemented"))
}

func (UnimplementedSnippetServiceHandler) UpdateSnippet(context.Context, *connect.Request[v1.UpdateSnippetRequest]) (*connect.Response[v1.Snippet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.UpdateSnippet is not implemented"))
}

func (UnimplementedSnippetServiceHandler) DeleteSnippet(context.Context, *connect.Request[v1.DeleteSnippetRequest]) (*connect.Response[v1.DeleteSnippetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.DeleteSnippet is not implemented"))
}

func (UnimplementedSnippetServiceHandler) SearchSnippets(context.Context, *connect.Request[v1.SearchSnippetsRequest]) (*connect.Response[v1.ListSnippetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.SearchSnippets is not implemented"))
}

func (UnimplementedSnippetServiceHandler) GetLanguageStats(context.Context, *connect.Request[v1.GetLanguageStatsRequest]) (*connect.Response[v1.GetLanguageStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.SnippetService.GetLanguageStats is not implemented"))
}
