// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devjournal/v1/user.proto

package devjournalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "devjournal/proto/devjournal/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "devjournal.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/devjournal.v1.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/devjournal.v1.AuthService/Login"
	// AuthServiceValidateTokenProcedure is the fully-qualified name of the AuthService's ValidateToken
	// RPC.
	AuthServiceValidateTokenProcedure = "/devjournal.v1.AuthService/ValidateToken"
	// AuthServiceGetProfileProcedure is the fully-qualified name of the AuthService's GetProfile RPC.
	AuthServiceGetProfileProcedure = "/devjournal.v1.AuthService/GetProfile"
	// AuthServiceUpdateProfileProcedure is the fully-qualified name of the AuthService's UpdateProfile
	// RPC.
	AuthServiceUpdateProfileProcedure = "/devjournal.v1.AuthService/UpdateProfile"
)

// AuthServiceClient is a client for the devjournal.v1.AuthService service.
type AuthServiceClient interface {
	// Register creates a new user account
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.AuthResponse], error)
	// Login authenticates a user and returns a token
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.AuthResponse], error)
	// ValidateToken validates a JWT token
	ValidateToken(context.Context, *connect.Request[v1.ValidateTokenRequest]) (*connect.Response[v1.User], error)
	// GetProfile retrieves the current user's profile
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.User], error)
	// UpdateProfile updates the current user's profile
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.User], error)
}

// NewAuthServiceClient constructs a client for the devjournal.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_devjournal_v1_user_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.AuthResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.AuthResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		validateToken: connect.NewClient[v1.ValidateTokenRequest, v1.User](
			httpClient,
			baseURL+AuthServiceValidateTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
			connect.WithClientOptions(opts...),
		),
		getProfile: connect.NewClient[v1.GetProfileRequest, v1.User](
			httpClient,
			baseURL+AuthServiceGetProfileProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.User](
			httpClient,
			baseURL+AuthServiceUpdateProfileProcedure,
			connect.WithSchema(authServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register      *connect.Client[v1.RegisterRequest, v1.AuthResponse]
	login         *connect.Client[v1.LoginRequest, v1.AuthResponse]
	validateToken *connect.Client[v1.ValidateTokenRequest, v1.User]
	getProfile    *connect.Client[v1.GetProfileRequest, v1.User]
	updateProfile *connect.Client[v1.UpdateProfileRequest, v1.User]
}

// Register calls devjournal.v1.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.AuthResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls devjournal.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.AuthResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// ValidateToken calls devjournal.v1.AuthService.ValidateToken.
func (c *authServiceClient) ValidateToken(ctx context.Context, req *connect.Request[v1.ValidateTokenRequest]) (*connect.Response[v1.User], error) {
	return c.validateToken.CallUnary(ctx, req)
}

// GetProfile calls devjournal.v1.AuthService.GetProfile.
func (c *authServiceClient) GetProfile(ctx context.Context, req *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.User], error) {
	return c.getProfile.CallUnary(ctx, req)
}

// UpdateProfile calls devjournal.v1.AuthService.UpdateProfile.
func (c *authServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.User], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the devjournal.v1.AuthService service.
type AuthServiceHandler interface {
	// Register creates a new user account
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.AuthResponse], error)
	// Login authenticates a user and returns a token
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.AuthResponse], error)
	// ValidateToken validates a JWT token
	ValidateToken(context.Context, *connect.Request[v1.ValidateTokenRequest]) (*connect.Response[v1.User], error)
	// GetProfile retrieves the current user's profile
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.User], error)
	// UpdateProfile updates the current user's profile
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.User], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_devjournal_v1_user_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceValidateTokenHandler := connect.NewUnaryHandler(
		AuthServiceValidateTokenProcedure,
		svc.ValidateToken,
		connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetProfileHandler := connect.NewUnaryHandler(
		AuthServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(authServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUpdateProfileHandler := connect.NewUnaryHandler(
		AuthServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(authServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devjournal.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceValidateTokenProcedure:
			authServiceValidateTokenHandler.ServeHTTP(w, r)
		case AuthServiceGetProfileProcedure:
			authServiceGetProfileHandler.ServeHTTP(w, r)
		case AuthServiceUpdateProfileProcedure:
			authServiceUpdateProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) ValidateToken(context.Context, *connect.Request[v1.ValidateTokenRequest]) (*connect.Response[v1.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.AuthService.ValidateToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.AuthService.GetProfile is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devjournal.v1.AuthService.UpdateProfile is not implemented"))
}
