// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: devjournal/v1/journal.proto

package devjournalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JournalEntry represents a learning journal entry
type JournalEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Mood          string                 `protobuf:"bytes,5,opt,name=mood,proto3" json:"mood,omitempty"` // excited, productive, frustrated, confused, accomplished
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{0}
}

func (x *JournalEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JournalEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JournalEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JournalEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *JournalEntry) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *JournalEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *JournalEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JournalEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateEntryRequest is the request to create a new entry
type CreateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mood          string                 `protobuf:"bytes,3,opt,name=mood,proto3" json:"mood,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateEntryRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *CreateEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// GetEntryRequest is the request to retrieve an entry
type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListEntriesRequest is the request to list entries with pagination
type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Mood          string                 `protobuf:"bytes,3,opt,name=mood,proto3" json:"mood,omitempty"` // Optional filter by mood
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{3}
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListEntriesRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

// ListEntriesResponse is the response containing a list of entries
type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*JournalEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{4}
}

func (x *ListEntriesResponse) GetEntries() []*JournalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateEntryRequest is the request to update an entry
type UpdateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mood          string                 `protobuf:"bytes,4,opt,name=mood,proto3" json:"mood,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryRequest) Reset() {
	*x = UpdateEntryRequest{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryRequest) ProtoMessage() {}

func (x *UpdateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateEntryRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *UpdateEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// DeleteEntryRequest is the request to delete an entry
type DeleteEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteEntryResponse is the response after deleting an entry
type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryResponse) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SearchEntriesRequest is the request to search entries
type SearchEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEntriesRequest) Reset() {
	*x = SearchEntriesRequest{}
	mi := &file_devjournal_v1_journal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntriesRequest) ProtoMessage() {}

func (x *SearchEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_journal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntriesRequest.ProtoReflect.Descriptor instead.
func (*SearchEntriesRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_journal_proto_rawDescGZIP(), []int{8}
}

func (x *SearchEntriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_devjournal_v1_journal_proto protoreflect.FileDescriptor

const file_devjournal_v1_journal_proto_rawDesc = "" +
	"\n" +
	"\x1bdevjournal/v1/journal.proto\x12\rdevjournal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\fJournalEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04mood\x18\x05 \x01(\tR\x04mood\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"l\n" +
	"\x12CreateEntryRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04mood\x18\x03 \x01(\tR\x04mood\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"!\n" +
	"\x0fGetEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x12ListEntriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04mood\x18\x03 \x01(\tR\x04mood\"m\n" +
	"\x13ListEntriesResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.devjournal.v1.JournalEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"|\n" +
	"\x12UpdateEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04mood\x18\x04 \x01(\tR\x04mood\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"$\n" +
	"\x12DeleteEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x14SearchEntriesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset2\xfd\x03\n" +
	"\x0eJournalService\x12M\n" +
	"\vCreateEntry\x12!.devjournal.v1.CreateEntryRequest\x1a\x1b.devjournal.v1.JournalEntry\x12G\n" +
	"\bGetEntry\x12\x1e.devjournal.v1.GetEntryRequest\x1a\x1b.devjournal.v1.JournalEntry\x12T\n" +
	"\vListEntries\x12!.devjournal.v1.ListEntriesRequest\x1a\".devjournal.v1.ListEntriesResponse\x12M\n" +
	"\vUpdateEntry\x12!.devjournal.v1.UpdateEntryRequest\x1a\x1b.devjournal.v1.JournalEntry\x12T\n" +
	"\vDeleteEntry\x12!.devjournal.v1.DeleteEntryRequest\x1a\".devjournal.v1.DeleteEntryResponse\x12X\n" +
	"\rSearchEntries\x12#.devjournal.v1.SearchEntriesRequest\x1a\".devjournal.v1.ListEntriesResponseB\xa3\x01\n" +
	"\x11com.devjournal.v1B\fJournalProtoP\x01Z+devjournal/proto/devjournal/v1;devjournalv1\xa2\x02\x03DXX\xaa\x02\rDevjournal.V1\xca\x02\rDevjournal\\V1\xe2\x02\x19Devjournal\\V1\\GPBMetadata\xea\x02\x0eDevjournal::V1b\x06proto3"

var (
	file_devjournal_v1_journal_proto_rawDescOnce sync.Once
	file_devjournal_v1_journal_proto_rawDescData []byte
)

func file_devjournal_v1_journal_proto_rawDescGZIP() []byte {
	file_devjournal_v1_journal_proto_rawDescOnce.Do(func() {
		file_devjournal_v1_journal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devjournal_v1_journal_proto_rawDesc), len(file_devjournal_v1_journal_proto_rawDesc)))
	})
	return file_devjournal_v1_journal_proto_rawDescData
}

var file_devjournal_v1_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_devjournal_v1_journal_proto_goTypes = []any{
	(*JournalEntry)(nil),          // 0: devjournal.v1.JournalEntry
	(*CreateEntryRequest)(nil),    // 1: devjournal.v1.CreateEntryRequest
	(*GetEntryRequest)(nil),       // 2: devjournal.v1.GetEntryRequest
	(*ListEntriesRequest)(nil),    // 3: devjournal.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),   // 4: devjournal.v1.ListEntriesResponse
	(*UpdateEntryRequest)(nil),    // 5: devjournal.v1.UpdateEntryRequest
	(*DeleteEntryRequest)(nil),    // 6: devjournal.v1.DeleteEntryRequest
	(*DeleteEntryResponse)(nil),   // 7: devjournal.v1.DeleteEntryResponse
	(*SearchEntriesRequest)(nil),  // 8: devjournal.v1.SearchEntriesRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_devjournal_v1_journal_proto_depIdxs = []int32{
	9, // 0: devjournal.v1.JournalEntry.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: devjournal.v1.JournalEntry.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: devjournal.v1.ListEntriesResponse.entries:type_name -> devjournal.v1.JournalEntry
	1, // 3: devjournal.v1.JournalService.CreateEntry:input_type -> devjournal.v1.CreateEntryRequest
	2, // 4: devjournal.v1.JournalService.GetEntry:input_type -> devjournal.v1.GetEntryRequest
	3, // 5: devjournal.v1.JournalService.ListEntries:input_type -> devjournal.v1.ListEntriesRequest
	5, // 6: devjournal.v1.JournalService.UpdateEntry:input_type -> devjournal.v1.UpdateEntryRequest
	6, // 7: devjournal.v1.JournalService.DeleteEntry:input_type -> devjournal.v1.DeleteEntryRequest
	8, // 8: devjournal.v1.JournalService.SearchEntries:input_type -> devjournal.v1.SearchEntriesRequest
	0, // 9: devjournal.v1.JournalService.CreateEntry:output_type -> devjournal.v1.JournalEntry
	0, // 10: devjournal.v1.JournalService.GetEntry:output_type -> devjournal.v1.JournalEntry
	4, // 11: devjournal.v1.JournalService.ListEntries:output_type -> devjournal.v1.ListEntriesResponse
	0, // 12: devjournal.v1.JournalService.UpdateEntry:output_type -> devjournal.v1.JournalEntry
	7, // 13: devjournal.v1.JournalService.DeleteEntry:output_type -> devjournal.v1.DeleteEntryResponse
	4, // 14: devjournal.v1.JournalService.SearchEntries:output_type -> devjournal.v1.ListEntriesResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_devjournal_v1_journal_proto_init() }
func file_devjournal_v1_journal_proto_init() {
	if File_devjournal_v1_journal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devjournal_v1_journal_proto_rawDesc), len(file_devjournal_v1_journal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devjournal_v1_journal_proto_goTypes,
		DependencyIndexes: file_devjournal_v1_journal_proto_depIdxs,
		MessageInfos:      file_devjournal_v1_journal_proto_msgTypes,
	}.Build()
	File_devjournal_v1_journal_proto = out.File
	file_devjournal_v1_journal_proto_goTypes = nil
	file_devjournal_v1_journal_proto_depIdxs = nil
}
