// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: devjournal/v1/progress.proto

package devjournalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgressService_GetSummary_FullMethodName         = "/devjournal.v1.ProgressService/GetSummary"
	ProgressService_GetTodayProgress_FullMethodName   = "/devjournal.v1.ProgressService/GetTodayProgress"
	ProgressService_GetWeeklyProgress_FullMethodName  = "/devjournal.v1.ProgressService/GetWeeklyProgress"
	ProgressService_GetMonthlyProgress_FullMethodName = "/devjournal.v1.ProgressService/GetMonthlyProgress"
	ProgressService_GetStreak_FullMethodName          = "/devjournal.v1.ProgressService/GetStreak"
)

// ProgressServiceClient is the client API for ProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProgressService provides learning progress tracking
type ProgressServiceClient interface {
	// GetSummary retrieves the overall progress summary
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*ProgressSummary, error)
	// GetTodayProgress retrieves today's progress
	GetTodayProgress(ctx context.Context, in *GetTodayProgressRequest, opts ...grpc.CallOption) (*DailyProgress, error)
	// GetWeeklyProgress retrieves the last 7 days of progress
	GetWeeklyProgress(ctx context.Context, in *GetWeeklyProgressRequest, opts ...grpc.CallOption) (*ProgressList, error)
	// GetMonthlyProgress retrieves the last 30 days of progress
	GetMonthlyProgress(ctx context.Context, in *GetMonthlyProgressRequest, opts ...grpc.CallOption) (*ProgressList, error)
	// GetStreak retrieves the current learning streak
	GetStreak(ctx context.Context, in *GetStreakRequest, opts ...grpc.CallOption) (*StreakResponse, error)
}

type progressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgressServiceClient(cc grpc.ClientConnInterface) ProgressServiceClient {
	return &progressServiceClient{cc}
}

func (c *progressServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*ProgressSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressSummary)
	err := c.cc.Invoke(ctx, ProgressService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetTodayProgress(ctx context.Context, in *GetTodayProgressRequest, opts ...grpc.CallOption) (*DailyProgress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyProgress)
	err := c.cc.Invoke(ctx, ProgressService_GetTodayProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetWeeklyProgress(ctx context.Context, in *GetWeeklyProgressRequest, opts ...grpc.CallOption) (*ProgressList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressList)
	err := c.cc.Invoke(ctx, ProgressService_GetWeeklyProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetMonthlyProgress(ctx context.Context, in *GetMonthlyProgressRequest, opts ...grpc.CallOption) (*ProgressList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressList)
	err := c.cc.Invoke(ctx, ProgressService_GetMonthlyProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressServiceClient) GetStreak(ctx context.Context, in *GetStreakRequest, opts ...grpc.CallOption) (*StreakResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreakResponse)
	err := c.cc.Invoke(ctx, ProgressService_GetStreak_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgressServiceServer is the server API for ProgressService service.
// All implementations must embed UnimplementedProgressServiceServer
// for forward compatibility.
//
// ProgressService provides learning progress tracking
type ProgressServiceServer interface {
	// GetSummary retrieves the overall progress summary
	GetSummary(context.Context, *GetSummaryRequest) (*ProgressSummary, error)
	// GetTodayProgress retrieves today's progress
	GetTodayProgress(context.Context, *GetTodayProgressRequest) (*DailyProgress, error)
	// GetWeeklyProgress retrieves the last 7 days of progress
	GetWeeklyProgress(context.Context, *GetWeeklyProgressRequest) (*ProgressList, error)
	// GetMonthlyProgress retrieves the last 30 days of progress
	GetMonthlyProgress(context.Context, *GetMonthlyProgressRequest) (*ProgressList, error)
	// GetStreak retrieves the current learning streak
	GetStreak(context.Context, *GetStreakRequest) (*StreakResponse, error)
	mustEmbedUnimplementedProgressServiceServer()
}

// UnimplementedProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgressServiceServer struct{}

func (UnimplementedProgressServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*ProgressSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedProgressServiceServer) GetTodayProgress(context.Context, *GetTodayProgressRequest) (*DailyProgress, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTodayProgress not implemented")
}
func (UnimplementedProgressServiceServer) GetWeeklyProgress(context.Context, *GetWeeklyProgressRequest) (*ProgressList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklyProgress not implemented")
}
func (UnimplementedProgressServiceServer) GetMonthlyProgress(context.Context, *GetMonthlyProgressRequest) (*ProgressList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyProgress not implemented")
}
func (UnimplementedProgressServiceServer) GetStreak(context.Context, *GetStreakRequest) (*StreakResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreak not implemented")
}
func (UnimplementedProgressServiceServer) mustEmbedUnimplementedProgressServiceServer() {}
func (UnimplementedProgressServiceServer) testEmbeddedByValue()                         {}

// UnsafeProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgressServiceServer will
// result in compilation errors.
type UnsafeProgressServiceServer interface {
	mustEmbedUnimplementedProgressServiceServer()
}

func RegisterProgressServiceServer(s grpc.ServiceRegistrar, srv ProgressServiceServer) {
	// If the following call panics, it indicates UnimplementedProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgressService_ServiceDesc, srv)
}

func _ProgressService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetTodayProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodayProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetTodayProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetTodayProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetTodayProgress(ctx, req.(*GetTodayProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetWeeklyProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetWeeklyProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetWeeklyProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetWeeklyProgress(ctx, req.(*GetWeeklyProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetMonthlyProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetMonthlyProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetMonthlyProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetMonthlyProgress(ctx, req.(*GetMonthlyProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgressService_GetStreak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreakRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgressServiceServer).GetStreak(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgressService_GetStreak_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgressServiceServer).GetStreak(ctx, req.(*GetStreakRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgressService_ServiceDesc is the grpc.ServiceDesc for ProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devjournal.v1.ProgressService",
	HandlerType: (*ProgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummary",
			Handler:    _ProgressService_GetSummary_Handler,
		},
		{
			MethodName: "GetTodayProgress",
			Handler:    _ProgressService_GetTodayProgress_Handler,
		},
		{
			MethodName: "GetWeeklyProgress",
			Handler:    _ProgressService_GetWeeklyProgress_Handler,
		},
		{
			MethodName: "GetMonthlyProgress",
			Handler:    _ProgressService_GetMonthlyProgress_Handler,
		},
		{
			MethodName: "GetStreak",
			Handler:    _ProgressService_GetStreak_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devjournal/v1/progress.proto",
}
