// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: devjournal/v1/progress.proto

package devjournalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DailyProgress represents learning progress for a single day
type DailyProgress struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	EntriesCount      int32                  `protobuf:"varint,4,opt,name=entries_count,json=entriesCount,proto3" json:"entries_count,omitempty"`
	SnippetsCount     int32                  `protobuf:"varint,5,opt,name=snippets_count,json=snippetsCount,proto3" json:"snippets_count,omitempty"`
	StreakDays        int32                  `protobuf:"varint,6,opt,name=streak_days,json=streakDays,proto3" json:"streak_days,omitempty"`
	TotalLearningTime int32                  `protobuf:"varint,7,opt,name=total_learning_time,json=totalLearningTime,proto3" json:"total_learning_time,omitempty"` // in minutes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DailyProgress) Reset() {
	*x = DailyProgress{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyProgress) ProtoMessage() {}

func (x *DailyProgress) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyProgress.ProtoReflect.Descriptor instead.
func (*DailyProgress) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{0}
}

func (x *DailyProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DailyProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DailyProgress) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *DailyProgress) GetEntriesCount() int32 {
	if x != nil {
		return x.EntriesCount
	}
	return 0
}

func (x *DailyProgress) GetSnippetsCount() int32 {
	if x != nil {
		return x.SnippetsCount
	}
	return 0
}

func (x *DailyProgress) GetStreakDays() int32 {
	if x != nil {
		return x.StreakDays
	}
	return 0
}

func (x *DailyProgress) GetTotalLearningTime() int32 {
	if x != nil {
		return x.TotalLearningTime
	}
	return 0
}

// ProgressSummary provides an overview of learning progress
type ProgressSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentStreak     int32                  `protobuf:"varint,1,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	LongestStreak     int32                  `protobuf:"varint,2,opt,name=longest_streak,json=longestStreak,proto3" json:"longest_streak,omitempty"`
	TotalEntries      int32                  `protobuf:"varint,3,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	TotalSnippets     int32                  `protobuf:"varint,4,opt,name=total_snippets,json=totalSnippets,proto3" json:"total_snippets,omitempty"`
	TotalLearningTime int32                  `protobuf:"varint,5,opt,name=total_learning_time,json=totalLearningTime,proto3" json:"total_learning_time,omitempty"` // in minutes
	ThisWeekEntries   int32                  `protobuf:"varint,6,opt,name=this_week_entries,json=thisWeekEntries,proto3" json:"this_week_entries,omitempty"`
	ThisMonthEntries  int32                  `protobuf:"varint,7,opt,name=this_month_entries,json=thisMonthEntries,proto3" json:"this_month_entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProgressSummary) Reset() {
	*x = ProgressSummary{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressSummary) ProtoMessage() {}

func (x *ProgressSummary) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressSummary.ProtoReflect.Descriptor instead.
func (*ProgressSummary) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{1}
}

func (x *ProgressSummary) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *ProgressSummary) GetLongestStreak() int32 {
	if x != nil {
		return x.LongestStreak
	}
	return 0
}

func (x *ProgressSummary) GetTotalEntries() int32 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *ProgressSummary) GetTotalSnippets() int32 {
	if x != nil {
		return x.TotalSnippets
	}
	return 0
}

func (x *ProgressSummary) GetTotalLearningTime() int32 {
	if x != nil {
		return x.TotalLearningTime
	}
	return 0
}

func (x *ProgressSummary) GetThisWeekEntries() int32 {
	if x != nil {
		return x.ThisWeekEntries
	}
	return 0
}

func (x *ProgressSummary) GetThisMonthEntries() int32 {
	if x != nil {
		return x.ThisMonthEntries
	}
	return 0
}

// ProgressList contains a list of daily progress records
type ProgressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      []*DailyProgress       `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressList) Reset() {
	*x = ProgressList{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressList) ProtoMessage() {}

func (x *ProgressList) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressList.ProtoReflect.Descriptor instead.
func (*ProgressList) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressList) GetProgress() []*DailyProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

// StreakResponse contains streak information
type StreakResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentStreak int32                  `protobuf:"varint,1,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	LongestStreak int32                  `protobuf:"varint,2,opt,name=longest_streak,json=longestStreak,proto3" json:"longest_streak,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreakResponse) Reset() {
	*x = StreakResponse{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreakResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreakResponse) ProtoMessage() {}

func (x *StreakResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreakResponse.ProtoReflect.Descriptor instead.
func (*StreakResponse) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{3}
}

func (x *StreakResponse) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *StreakResponse) GetLongestStreak() int32 {
	if x != nil {
		return x.LongestStreak
	}
	return 0
}

func (x *StreakResponse) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

// Request messages
type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{4}
}

type GetTodayProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayProgressRequest) Reset() {
	*x = GetTodayProgressRequest{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayProgressRequest) ProtoMessage() {}

func (x *GetTodayProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayProgressRequest.ProtoReflect.Descriptor instead.
func (*GetTodayProgressRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{5}
}

type GetWeeklyProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyProgressRequest) Reset() {
	*x = GetWeeklyProgressRequest{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyProgressRequest) ProtoMessage() {}

func (x *GetWeeklyProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyProgressRequest.ProtoReflect.Descriptor instead.
func (*GetWeeklyProgressRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{6}
}

type GetMonthlyProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyProgressRequest) Reset() {
	*x = GetMonthlyProgressRequest{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyProgressRequest) ProtoMessage() {}

func (x *GetMonthlyProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyProgressRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyProgressRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{7}
}

type GetStreakRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreakRequest) Reset() {
	*x = GetStreakRequest{}
	mi := &file_devjournal_v1_progress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreakRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreakRequest) ProtoMessage() {}

func (x *GetStreakRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_progress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreakRequest.ProtoReflect.Descriptor instead.
func (*GetStreakRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_progress_proto_rawDescGZIP(), []int{8}
}

var File_devjournal_v1_progress_proto protoreflect.FileDescriptor

const file_devjournal_v1_progress_proto_rawDesc = "" +
	"\n" +
	"\x1cdevjournal/v1/progress.proto\x12\rdevjournal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\rDailyProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12#\n" +
	"\rentries_count\x18\x04 \x01(\x05R\fentriesCount\x12%\n" +
	"\x0esnippets_count\x18\x05 \x01(\x05R\rsnippetsCount\x12\x1f\n" +
	"\vstreak_days\x18\x06 \x01(\x05R\n" +
	"streakDays\x12.\n" +
	"\x13total_learning_time\x18\a \x01(\x05R\x11totalLearningTime\"\xb5\x02\n" +
	"\x0fProgressSummary\x12%\n" +
	"\x0ecurrent_streak\x18\x01 \x01(\x05R\rcurrentStreak\x12%\n" +
	"\x0elongest_streak\x18\x02 \x01(\x05R\rlongestStreak\x12#\n" +
	"\rtotal_entries\x18\x03 \x01(\x05R\ftotalEntries\x12%\n" +
	"\x0etotal_snippets\x18\x04 \x01(\x05R\rtotalSnippets\x12.\n" +
	"\x13total_learning_time\x18\x05 \x01(\x05R\x11totalLearningTime\x12*\n" +
	"\x11this_week_entries\x18\x06 \x01(\x05R\x0fthisWeekEntries\x12,\n" +
	"\x12this_month_entries\x18\a \x01(\x05R\x10thisMonthEntries\"H\n" +
	"\fProgressList\x128\n" +
	"\bprogress\x18\x01 \x03(\v2\x1c.devjournal.v1.DailyProgressR\bprogress\"\x9f\x01\n" +
	"\x0eStreakResponse\x12%\n" +
	"\x0ecurrent_streak\x18\x01 \x01(\x05R\rcurrentStreak\x12%\n" +
	"\x0elongest_streak\x18\x02 \x01(\x05R\rlongestStreak\x12?\n" +
	"\rlast_activity\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\x13\n" +
	"\x11GetSummaryRequest\"\x19\n" +
	"\x17GetTodayProgressRequest\"\x1a\n" +
	"\x18GetWeeklyProgressRequest\"\x1b\n" +
	"\x19GetMonthlyProgressRequest\"\x12\n" +
	"\x10GetStreakRequest2\xc0\x03\n" +
	"\x0fProgressService\x12N\n" +
	"\n" +
	"GetSummary\x12 .devjournal.v1.GetSummaryRequest\x1a\x1e.devjournal.v1.ProgressSummary\x12X\n" +
	"\x10GetTodayProgress\x12&.devjournal.v1.GetTodayProgressRequest\x1a\x1c.devjournal.v1.DailyProgress\x12Y\n" +
	"\x11GetWeeklyProgress\x12'.devjournal.v1.GetWeeklyProgressRequest\x1a\x1b.devjournal.v1.ProgressList\x12[\n" +
	"\x12GetMonthlyProgress\x12(.devjournal.v1.GetMonthlyProgressRequest\x1a\x1b.devjournal.v1.ProgressList\x12K\n" +
	"\tGetStreak\x12\x1f.devjournal.v1.GetStreakRequest\x1a\x1d.devjournal.v1.StreakResponseB\xa4\x01\n" +
	"\x11com.devjournal.v1B\rProgressProtoP\x01Z+devjournal/proto/devjournal/v1;devjournalv1\xa2\x02\x03DXX\xaa\x02\rDevjournal.V1\xca\x02\rDevjournal\\V1\xe2\x02\x19Devjournal\\V1\\GPBMetadata\xea\x02\x0eDevjournal::V1b\x06proto3"

var (
	file_devjournal_v1_progress_proto_rawDescOnce sync.Once
	file_devjournal_v1_progress_proto_rawDescData []byte
)

func file_devjournal_v1_progress_proto_rawDescGZIP() []byte {
	file_devjournal_v1_progress_proto_rawDescOnce.Do(func() {
		file_devjournal_v1_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devjournal_v1_progress_proto_rawDesc), len(file_devjournal_v1_progress_proto_rawDesc)))
	})
	return file_devjournal_v1_progress_proto_rawDescData
}

var file_devjournal_v1_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_devjournal_v1_progress_proto_goTypes = []any{
	(*DailyProgress)(nil),             // 0: devjournal.v1.DailyProgress
	(*ProgressSummary)(nil),           // 1: devjournal.v1.ProgressSummary
	(*ProgressList)(nil),              // 2: devjournal.v1.ProgressList
	(*StreakResponse)(nil),            // 3: devjournal.v1.StreakResponse
	(*GetSummaryRequest)(nil),         // 4: devjournal.v1.GetSummaryRequest
	(*GetTodayProgressRequest)(nil),   // 5: devjournal.v1.GetTodayProgressRequest
	(*GetWeeklyProgressRequest)(nil),  // 6: devjournal.v1.GetWeeklyProgressRequest
	(*GetMonthlyProgressRequest)(nil), // 7: devjournal.v1.GetMonthlyProgressRequest
	(*GetStreakRequest)(nil),          // 8: devjournal.v1.GetStreakRequest
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_devjournal_v1_progress_proto_depIdxs = []int32{
	9, // 0: devjournal.v1.DailyProgress.date:type_name -> google.protobuf.Timestamp
	0, // 1: devjournal.v1.ProgressList.progress:type_name -> devjournal.v1.DailyProgress
	9, // 2: devjournal.v1.StreakResponse.last_activity:type_name -> google.protobuf.Timestamp
	4, // 3: devjournal.v1.ProgressService.GetSummary:input_type -> devjournal.v1.GetSummaryRequest
	5, // 4: devjournal.v1.ProgressService.GetTodayProgress:input_type -> devjournal.v1.GetTodayProgressRequest
	6, // 5: devjournal.v1.ProgressService.GetWeeklyProgress:input_type -> devjournal.v1.GetWeeklyProgressRequest
	7, // 6: devjournal.v1.ProgressService.GetMonthlyProgress:input_type -> devjournal.v1.GetMonthlyProgressRequest
	8, // 7: devjournal.v1.ProgressService.GetStreak:input_type -> devjournal.v1.GetStreakRequest
	1, // 8: devjournal.v1.ProgressService.GetSummary:output_type -> devjournal.v1.ProgressSummary
	0, // 9: devjournal.v1.ProgressService.GetTodayProgress:output_type -> devjournal.v1.DailyProgress
	2, // 10: devjournal.v1.ProgressService.GetWeeklyProgress:output_type -> devjournal.v1.ProgressList
	2, // 11: devjournal.v1.ProgressService.GetMonthlyProgress:output_type -> devjournal.v1.ProgressList
	3, // 12: devjournal.v1.ProgressService.GetStreak:output_type -> devjournal.v1.StreakResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_devjournal_v1_progress_proto_init() }
func file_devjournal_v1_progress_proto_init() {
	if File_devjournal_v1_progress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devjournal_v1_progress_proto_rawDesc), len(file_devjournal_v1_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devjournal_v1_progress_proto_goTypes,
		DependencyIndexes: file_devjournal_v1_progress_proto_depIdxs,
		MessageInfos:      file_devjournal_v1_progress_proto_msgTypes,
	}.Build()
	File_devjournal_v1_progress_proto = out.File
	file_devjournal_v1_progress_proto_goTypes = nil
	file_devjournal_v1_progress_proto_depIdxs = nil
}
