// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: devjournal/v1/snippet.proto

package devjournalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnippetService_CreateSnippet_FullMethodName    = "/devjournal.v1.SnippetService/CreateSnippet"
	SnippetService_GetSnippet_FullMethodName       = "/devjournal.v1.SnippetService/GetSnippet"
	SnippetService_ListSnippets_FullMethodName     = "/devjournal.v1.SnippetService/ListSnippets"
	SnippetService_UpdateSnippet_FullMethodName    = "/devjournal.v1.SnippetService/UpdateSnippet"
	SnippetService_DeleteSnippet_FullMethodName    = "/devjournal.v1.SnippetService/DeleteSnippet"
	SnippetService_SearchSnippets_FullMethodName   = "/devjournal.v1.SnippetService/SearchSnippets"
	SnippetService_GetLanguageStats_FullMethodName = "/devjournal.v1.SnippetService/GetLanguageStats"
)

// SnippetServiceClient is the client API for SnippetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnippetService provides CRUD operations for code snippets
type SnippetServiceClient interface {
	// CreateSnippet creates a new code snippet
	CreateSnippet(ctx context.Context, in *CreateSnippetRequest, opts ...grpc.CallOption) (*Snippet, error)
	// GetSnippet retrieves a single snippet by ID
	GetSnippet(ctx context.Context, in *GetSnippetRequest, opts ...grpc.CallOption) (*Snippet, error)
	// ListSnippets retrieves a paginated list of snippets
	ListSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	// UpdateSnippet updates an existing snippet
	UpdateSnippet(ctx context.Context, in *UpdateSnippetRequest, opts ...grpc.CallOption) (*Snippet, error)
	// DeleteSnippet removes a snippet
	DeleteSnippet(ctx context.Context, in *DeleteSnippetRequest, opts ...grpc.CallOption) (*DeleteSnippetResponse, error)
	// SearchSnippets performs full-text search on snippets
	SearchSnippets(ctx context.Context, in *SearchSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	// GetLanguageStats returns snippet counts grouped by language
	GetLanguageStats(ctx context.Context, in *GetLanguageStatsRequest, opts ...grpc.CallOption) (*GetLanguageStatsResponse, error)
}

type snippetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnippetServiceClient(cc grpc.ClientConnInterface) SnippetServiceClient {
	return &snippetServiceClient{cc}
}

func (c *snippetServiceClient) CreateSnippet(ctx context.Context, in *CreateSnippetRequest, opts ...grpc.CallOption) (*Snippet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snippet)
	err := c.cc.Invoke(ctx, SnippetService_CreateSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetServiceClient) GetSnippet(ctx context.Context, in *GetSnippetRequest, opts ...grpc.CallOption) (*Snippet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snippet)
	err := c.cc.Invoke(ctx, SnippetService_GetSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetServiceClient) ListSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, SnippetService_ListSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetServiceClient) UpdateSnippet(ctx context.Context, in *UpdateSnippetRequest, opts ...grpc.CallOption) (*Snippet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snippet)
	err := c.cc.Invoke(ctx, SnippetService_UpdateSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetServiceClient) DeleteSnippet(ctx context.Context, in *DeleteSnippetRequest, opts ...grpc.CallOption) (*DeleteSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnippetResponse)
	err := c.cc.Invoke(ctx, SnippetService_DeleteSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetServiceClient) SearchSnippets(ctx context.Context, in *SearchSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, SnippetService_SearchSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetServiceClient) GetLanguageStats(ctx context.Context, in *GetLanguageStatsRequest, opts ...grpc.CallOption) (*GetLanguageStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLanguageStatsResponse)
	err := c.cc.Invoke(ctx, SnippetService_GetLanguageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnippetServiceServer is the server API for SnippetService service.
// All implementations must embed UnimplementedSnippetServiceServer
// for forward compatibility.
//
// SnippetService provides CRUD operations for code snippets
type SnippetServiceServer interface {
	// CreateSnippet creates a new code snippet
	CreateSnippet(context.Context, *CreateSnippetRequest) (*Snippet, error)
	// GetSnippet retrieves a single snippet by ID
	GetSnippet(context.Context, *GetSnippetRequest) (*Snippet, error)
	// ListSnippets retrieves a paginated list of snippets
	ListSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error)
	// UpdateSnippet updates an existing snippet
	UpdateSnippet(context.Context, *UpdateSnippetRequest) (*Snippet, error)
	// DeleteSnippet removes a snippet
	DeleteSnippet(context.Context, *DeleteSnippetRequest) (*DeleteSnippetResponse, error)
	// SearchSnippets performs full-text search on snippets
	SearchSnippets(context.Context, *SearchSnippetsRequest) (*ListSnippetsResponse, error)
	// GetLanguageStats returns snippet counts grouped by language
	GetLanguageStats(context.Context, *GetLanguageStatsRequest) (*GetLanguageStatsResponse, error)
	mustEmbedUnimplementedSnippetServiceServer()
}

// UnimplementedSnippetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnippetServiceServer struct{}

func (UnimplementedSnippetServiceServer) CreateSnippet(context.Context, *CreateSnippetRequest) (*Snippet, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnippet not implemented")
}
func (UnimplementedSnippetServiceServer) GetSnippet(context.Context, *GetSnippetRequest) (*Snippet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnippet not implemented")
}
func (UnimplementedSnippetServiceServer) ListSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnippets not implemented")
}
func (UnimplementedSnippetServiceServer) UpdateSnippet(context.Context, *UpdateSnippetRequest) (*Snippet, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSnippet not implemented")
}
func (UnimplementedSnippetServiceServer) DeleteSnippet(context.Context, *DeleteSnippetRequest) (*DeleteSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnippet not implemented")
}
func (UnimplementedSnippetServiceServer) SearchSnippets(context.Context, *SearchSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSnippets not implemented")
}
func (UnimplementedSnippetServiceServer) GetLanguageStats(context.Context, *GetLanguageStatsRequest) (*GetLanguageStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLanguageStats not implemented")
}
func (UnimplementedSnippetServiceServer) mustEmbedUnimplementedSnippetServiceServer() {}
func (UnimplementedSnippetServiceServer) testEmbeddedByValue()                        {}

// UnsafeSnippetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnippetServiceServer will
// result in compilation errors.
type UnsafeSnippetServiceServer interface {
	mustEmbedUnimplementedSnippetServiceServer()
}

func RegisterSnippetServiceServer(s grpc.ServiceRegistrar, srv SnippetServiceServer) {
	// If the following call panics, it indicates UnimplementedSnippetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnippetService_ServiceDesc, srv)
}

func _SnippetService_CreateSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).CreateSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_CreateSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).CreateSnippet(ctx, req.(*CreateSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetService_GetSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).GetSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_GetSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).GetSnippet(ctx, req.(*GetSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetService_ListSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).ListSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_ListSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).ListSnippets(ctx, req.(*ListSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetService_UpdateSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).UpdateSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_UpdateSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).UpdateSnippet(ctx, req.(*UpdateSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetService_DeleteSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).DeleteSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_DeleteSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).DeleteSnippet(ctx, req.(*DeleteSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetService_SearchSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).SearchSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_SearchSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).SearchSnippets(ctx, req.(*SearchSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetService_GetLanguageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLanguageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetServiceServer).GetLanguageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetService_GetLanguageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetServiceServer).GetLanguageStats(ctx, req.(*GetLanguageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnippetService_ServiceDesc is the grpc.ServiceDesc for SnippetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnippetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devjournal.v1.SnippetService",
	HandlerType: (*SnippetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnippet",
			Handler:    _SnippetService_CreateSnippet_Handler,
		},
		{
			MethodName: "GetSnippet",
			Handler:    _SnippetService_GetSnippet_Handler,
		},
		{
			MethodName: "ListSnippets",
			Handler:    _SnippetService_ListSnippets_Handler,
		},
		{
			MethodName: "UpdateSnippet",
			Handler:    _SnippetService_UpdateSnippet_Handler,
		},
		{
			MethodName: "DeleteSnippet",
			Handler:    _SnippetService_DeleteSnippet_Handler,
		},
		{
			MethodName: "SearchSnippets",
			Handler:    _SnippetService_SearchSnippets_Handler,
		},
		{
			MethodName: "GetLanguageStats",
			Handler:    _SnippetService_GetLanguageStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devjournal/v1/snippet.proto",
}
