// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: devjournal/v1/snippet.proto

package devjournalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snippet represents a code snippet stored in MongoDB
type Snippet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"` // typescript, go, python, etc.
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"` // Flexible metadata fields
	IsPublic      bool                   `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	ViewsCount    int32                  `protobuf:"varint,10,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snippet) Reset() {
	*x = Snippet{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snippet) ProtoMessage() {}

func (x *Snippet) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snippet.ProtoReflect.Descriptor instead.
func (*Snippet) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{0}
}

func (x *Snippet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snippet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Snippet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Snippet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Snippet) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Snippet) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Snippet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Snippet) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Snippet) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Snippet) GetViewsCount() int32 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *Snippet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Snippet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateSnippetRequest is the request to create a new snippet
type CreateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetRequest) Reset() {
	*x = CreateSnippetRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetRequest) ProtoMessage() {}

func (x *CreateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetRequest.ProtoReflect.Descriptor instead.
func (*CreateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSnippetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSnippetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSnippetRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateSnippetRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateSnippetRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateSnippetRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSnippetRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// GetSnippetRequest is the request to retrieve a snippet
type GetSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnippetRequest) Reset() {
	*x = GetSnippetRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnippetRequest) ProtoMessage() {}

func (x *GetSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnippetRequest.ProtoReflect.Descriptor instead.
func (*GetSnippetRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{2}
}

func (x *GetSnippetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListSnippetsRequest is the request to list snippets with pagination
type ListSnippetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // Optional filter by language
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`         // Optional filter by tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnippetsRequest) Reset() {
	*x = ListSnippetsRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnippetsRequest) ProtoMessage() {}

func (x *ListSnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnippetsRequest.ProtoReflect.Descriptor instead.
func (*ListSnippetsRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{3}
}

func (x *ListSnippetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSnippetsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSnippetsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListSnippetsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ListSnippetsResponse is the response containing a list of snippets
type ListSnippetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*Snippet             `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnippetsResponse) Reset() {
	*x = ListSnippetsResponse{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnippetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnippetsResponse) ProtoMessage() {}

func (x *ListSnippetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnippetsResponse.ProtoReflect.Descriptor instead.
func (*ListSnippetsResponse) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{4}
}

func (x *ListSnippetsResponse) GetSnippets() []*Snippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *ListSnippetsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateSnippetRequest is the request to update a snippet
type UpdateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IsPublic      bool                   `protobuf:"varint,8,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnippetRequest) Reset() {
	*x = UpdateSnippetRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnippetRequest) ProtoMessage() {}

func (x *UpdateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnippetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSnippetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSnippetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSnippetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSnippetRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateSnippetRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateSnippetRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateSnippetRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateSnippetRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// DeleteSnippetRequest is the request to delete a snippet
type DeleteSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnippetRequest) Reset() {
	*x = DeleteSnippetRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnippetRequest) ProtoMessage() {}

func (x *DeleteSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnippetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnippetRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSnippetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSnippetResponse is the response after deleting a snippet
type DeleteSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnippetResponse) Reset() {
	*x = DeleteSnippetResponse{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnippetResponse) ProtoMessage() {}

func (x *DeleteSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnippetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnippetResponse) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSnippetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SearchSnippetsRequest is the request to search snippets
type SearchSnippetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSnippetsRequest) Reset() {
	*x = SearchSnippetsRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSnippetsRequest) ProtoMessage() {}

func (x *SearchSnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSnippetsRequest.ProtoReflect.Descriptor instead.
func (*SearchSnippetsRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{8}
}

func (x *SearchSnippetsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSnippetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSnippetsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetLanguageStatsRequest is the request to get language statistics
type GetLanguageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguageStatsRequest) Reset() {
	*x = GetLanguageStatsRequest{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageStatsRequest) ProtoMessage() {}

func (x *GetLanguageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLanguageStatsRequest) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{9}
}

// GetLanguageStatsResponse contains snippet counts by language
type GetLanguageStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LanguageCounts map[string]int64       `protobuf:"bytes,1,rep,name=language_counts,json=languageCounts,proto3" json:"language_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLanguageStatsResponse) Reset() {
	*x = GetLanguageStatsResponse{}
	mi := &file_devjournal_v1_snippet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageStatsResponse) ProtoMessage() {}

func (x *GetLanguageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devjournal_v1_snippet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLanguageStatsResponse) Descriptor() ([]byte, []int) {
	return file_devjournal_v1_snippet_proto_rawDescGZIP(), []int{10}
}

func (x *GetLanguageStatsResponse) GetLanguageCounts() map[string]int64 {
	if x != nil {
		return x.LanguageCounts
	}
	return nil
}

var File_devjournal_v1_snippet_proto protoreflect.FileDescriptor

const file_devjournal_v1_snippet_proto_rawDesc = "" +
	"\n" +
	"\x1bdevjournal/v1/snippet.proto\x12\rdevjournal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x97\x03\n" +
	"\aSnippet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1b\n" +
	"\tis_public\x18\t \x01(\bR\bisPublic\x12\x1f\n" +
	"\vviews_count\x18\n" +
	" \x01(\x05R\n" +
	"viewsCount\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe4\x01\n" +
	"\x14CreateSnippetRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\"#\n" +
	"\x11GetSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"s\n" +
	"\x13ListSnippetsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"k\n" +
	"\x14ListSnippetsResponse\x122\n" +
	"\bsnippets\x18\x01 \x03(\v2\x16.devjournal.v1.SnippetR\bsnippets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xf4\x01\n" +
	"\x14UpdateSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1b\n" +
	"\tis_public\x18\b \x01(\bR\bisPublic\"&\n" +
	"\x14DeleteSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteSnippetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x15SearchSnippetsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x19\n" +
	"\x17GetLanguageStatsRequest\"\xc3\x01\n" +
	"\x18GetLanguageStatsResponse\x12d\n" +
	"\x0flanguage_counts\x18\x01 \x03(\v2;.devjournal.v1.GetLanguageStatsResponse.LanguageCountsEntryR\x0elanguageCounts\x1aA\n" +
	"\x13LanguageCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xeb\x04\n" +
	"\x0eSnippetService\x12L\n" +
	"\rCreateSnippet\x12#.devjournal.v1.CreateSnippetRequest\x1a\x16.devjournal.v1.Snippet\x12F\n" +
	"\n" +
	"GetSnippet\x12 .devjournal.v1.GetSnippetRequest\x1a\x16.devjournal.v1.Snippet\x12W\n" +
	"\fListSnippets\x12\".devjournal.v1.ListSnippetsRequest\x1a#.devjournal.v1.ListSnippetsResponse\x12L\n" +
	"\rUpdateSnippet\x12#.devjournal.v1.UpdateSnippetRequest\x1a\x16.devjournal.v1.Snippet\x12Z\n" +
	"\rDeleteSnippet\x12#.devjournal.v1.DeleteSnippetRequest\x1a$.devjournal.v1.DeleteSnippetResponse\x12[\n" +
	"\x0eSearchSnippets\x12$.devjournal.v1.SearchSnippetsRequest\x1a#.devjournal.v1.ListSnippetsResponse\x12c\n" +
	"\x10GetLanguageStats\x12&.devjournal.v1.GetLanguageStatsRequest\x1a'.devjournal.v1.GetLanguageStatsResponseB\xa3\x01\n" +
	"\x11com.devjournal.v1B\fSnippetProtoP\x01Z+devjournal/proto/devjournal/v1;devjournalv1\xa2\x02\x03DXX\xaa\x02\rDevjournal.V1\xca\x02\rDevjournal\\V1\xe2\x02\x19Devjournal\\V1\\GPBMetadata\xea\x02\x0eDevjournal::V1b\x06proto3"

var (
	file_devjournal_v1_snippet_proto_rawDescOnce sync.Once
	file_devjournal_v1_snippet_proto_rawDescData []byte
)

func file_devjournal_v1_snippet_proto_rawDescGZIP() []byte {
	file_devjournal_v1_snippet_proto_rawDescOnce.Do(func() {
		file_devjournal_v1_snippet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devjournal_v1_snippet_proto_rawDesc), len(file_devjournal_v1_snippet_proto_rawDesc)))
	})
	return file_devjournal_v1_snippet_proto_rawDescData
}

var file_devjournal_v1_snippet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_devjournal_v1_snippet_proto_goTypes = []any{
	(*Snippet)(nil),                  // 0: devjournal.v1.Snippet
	(*CreateSnippetRequest)(nil),     // 1: devjournal.v1.CreateSnippetRequest
	(*GetSnippetRequest)(nil),        // 2: devjournal.v1.GetSnippetRequest
	(*ListSnippetsRequest)(nil),      // 3: devjournal.v1.ListSnippetsRequest
	(*ListSnippetsResponse)(nil),     // 4: devjournal.v1.ListSnippetsResponse
	(*UpdateSnippetRequest)(nil),     // 5: devjournal.v1.UpdateSnippetRequest
	(*DeleteSnippetRequest)(nil),     // 6: devjournal.v1.DeleteSnippetRequest
	(*DeleteSnippetResponse)(nil),    // 7: devjournal.v1.DeleteSnippetResponse
	(*SearchSnippetsRequest)(nil),    // 8: devjournal.v1.SearchSnippetsRequest
	(*GetLanguageStatsRequest)(nil),  // 9: devjournal.v1.GetLanguageStatsRequest
	(*GetLanguageStatsResponse)(nil), // 10: devjournal.v1.GetLanguageStatsResponse
	nil,                              // 11: devjournal.v1.GetLanguageStatsResponse.LanguageCountsEntry
	(*structpb.Struct)(nil),          // 12: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_devjournal_v1_snippet_proto_depIdxs = []int32{
	12, // 0: devjournal.v1.Snippet.metadata:type_name -> google.protobuf.Struct
	13, // 1: devjournal.v1.Snippet.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: devjournal.v1.Snippet.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: devjournal.v1.CreateSnippetRequest.metadata:type_name -> google.protobuf.Struct
	0,  // 4: devjournal.v1.ListSnippetsResponse.snippets:type_name -> devjournal.v1.Snippet
	12, // 5: devjournal.v1.UpdateSnippetRequest.metadata:type_name -> google.protobuf.Struct
	11, // 6: devjournal.v1.GetLanguageStatsResponse.language_counts:type_name -> devjournal.v1.GetLanguageStatsResponse.LanguageCountsEntry
	1,  // 7: devjournal.v1.SnippetService.CreateSnippet:input_type -> devjournal.v1.CreateSnippetRequest
	2,  // 8: devjournal.v1.SnippetService.GetSnippet:input_type -> devjournal.v1.GetSnippetRequest
	3,  // 9: devjournal.v1.SnippetService.ListSnippets:input_type -> devjournal.v1.ListSnippetsRequest
	5,  // 10: devjournal.v1.SnippetService.UpdateSnippet:input_type -> devjournal.v1.UpdateSnippetRequest
	6,  // 11: devjournal.v1.SnippetService.DeleteSnippet:input_type -> devjournal.v1.DeleteSnippetRequest
	8,  // 12: devjournal.v1.SnippetService.SearchSnippets:input_type -> devjournal.v1.SearchSnippetsRequest
	9,  // 13: devjournal.v1.SnippetService.GetLanguageStats:input_type -> devjournal.v1.GetLanguageStatsRequest
	0,  // 14: devjournal.v1.SnippetService.CreateSnippet:output_type -> devjournal.v1.Snippet
	0,  // 15: devjournal.v1.SnippetService.GetSnippet:output_type -> devjournal.v1.Snippet
	4,  // 16: devjournal.v1.SnippetService.ListSnippets:output_type -> devjournal.v1.ListSnippetsResponse
	0,  // 17: devjournal.v1.SnippetService.UpdateSnippet:output_type -> devjournal.v1.Snippet
	7,  // 18: devjournal.v1.SnippetService.DeleteSnippet:output_type -> devjournal.v1.DeleteSnippetResponse
	4,  // 19: devjournal.v1.SnippetService.SearchSnippets:output_type -> devjournal.v1.ListSnippetsResponse
	10, // 20: devjournal.v1.SnippetService.GetLanguageStats:output_type -> devjournal.v1.GetLanguageStatsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_devjournal_v1_snippet_proto_init() }
func file_devjournal_v1_snippet_proto_init() {
	if File_devjournal_v1_snippet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devjournal_v1_snippet_proto_rawDesc), len(file_devjournal_v1_snippet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devjournal_v1_snippet_proto_goTypes,
		DependencyIndexes: file_devjournal_v1_snippet_proto_depIdxs,
		MessageInfos:      file_devjournal_v1_snippet_proto_msgTypes,
	}.Build()
	File_devjournal_v1_snippet_proto = out.File
	file_devjournal_v1_snippet_proto_goTypes = nil
	file_devjournal_v1_snippet_proto_depIdxs = nil
}
