// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/journal.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateEntryRequest, DeleteEntryRequest, DeleteEntryResponse, GetEntryRequest, JournalEntry, ListEntriesRequest, ListEntriesResponse, SearchEntriesRequest, UpdateEntryRequest } from "./journal_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * JournalService provides CRUD operations for journal entries
 *
 * @generated from service devjournal.v1.JournalService
 */
export const JournalService = {
  typeName: "devjournal.v1.JournalService",
  methods: {
    /**
     * CreateEntry creates a new journal entry
     *
     * @generated from rpc devjournal.v1.JournalService.CreateEntry
     */
    createEntry: {
      name: "CreateEntry",
      I: CreateEntryRequest,
      O: JournalEntry,
      kind: MethodKind.Unary,
    },
    /**
     * GetEntry retrieves a single journal entry by ID
     *
     * @generated from rpc devjournal.v1.JournalService.GetEntry
     */
    getEntry: {
      name: "GetEntry",
      I: GetEntryRequest,
      O: JournalEntry,
      kind: MethodKind.Unary,
    },
    /**
     * ListEntries retrieves a paginated list of journal entries
     *
     * @generated from rpc devjournal.v1.JournalService.ListEntries
     */
    listEntries: {
      name: "ListEntries",
      I: ListEntriesRequest,
      O: ListEntriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateEntry updates an existing journal entry
     *
     * @generated from rpc devjournal.v1.JournalService.UpdateEntry
     */
    updateEntry: {
      name: "UpdateEntry",
      I: UpdateEntryRequest,
      O: JournalEntry,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteEntry removes a journal entry
     *
     * @generated from rpc devjournal.v1.JournalService.DeleteEntry
     */
    deleteEntry: {
      name: "DeleteEntry",
      I: DeleteEntryRequest,
      O: DeleteEntryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SearchEntries searches journal entries by title or content
     *
     * @generated from rpc devjournal.v1.JournalService.SearchEntries
     */
    searchEntries: {
      name: "SearchEntries",
      I: SearchEntriesRequest,
      O: ListEntriesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

