// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/journal.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file devjournal/v1/journal.proto.
 */
export const file_devjournal_v1_journal: GenFile = /*@__PURE__*/
  fileDesc("ChtkZXZqb3VybmFsL3YxL2pvdXJuYWwucHJvdG8SDWRldmpvdXJuYWwudjEixwEKDEpvdXJuYWxFbnRyeRIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEg0KBXRpdGxlGAMgASgJEg8KB2NvbnRlbnQYBCABKAkSDAoEbW9vZBgFIAEoCRIMCgR0YWdzGAYgAygJEi4KCmNyZWF0ZWRfYXQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIlAKEkNyZWF0ZUVudHJ5UmVxdWVzdBINCgV0aXRsZRgBIAEoCRIPCgdjb250ZW50GAIgASgJEgwKBG1vb2QYAyABKAkSDAoEdGFncxgEIAMoCSIdCg9HZXRFbnRyeVJlcXVlc3QSCgoCaWQYASABKAkiQQoSTGlzdEVudHJpZXNSZXF1ZXN0Eg0KBWxpbWl0GAEgASgFEg4KBm9mZnNldBgCIAEoBRIMCgRtb29kGAMgASgJIlgKE0xpc3RFbnRyaWVzUmVzcG9uc2USLAoHZW50cmllcxgBIAMoCzIbLmRldmpvdXJuYWwudjEuSm91cm5hbEVudHJ5EhMKC3RvdGFsX2NvdW50GAIgASgFIlwKElVwZGF0ZUVudHJ5UmVxdWVzdBIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRIPCgdjb250ZW50GAMgASgJEgwKBG1vb2QYBCABKAkSDAoEdGFncxgFIAMoCSIgChJEZWxldGVFbnRyeVJlcXVlc3QSCgoCaWQYASABKAkiJgoTRGVsZXRlRW50cnlSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIkQKFFNlYXJjaEVudHJpZXNSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEg0KBWxpbWl0GAIgASgFEg4KBm9mZnNldBgDIAEoBTL9AwoOSm91cm5hbFNlcnZpY2USTQoLQ3JlYXRlRW50cnkSIS5kZXZqb3VybmFsLnYxLkNyZWF0ZUVudHJ5UmVxdWVzdBobLmRldmpvdXJuYWwudjEuSm91cm5hbEVudHJ5EkcKCEdldEVudHJ5Eh4uZGV2am91cm5hbC52MS5HZXRFbnRyeVJlcXVlc3QaGy5kZXZqb3VybmFsLnYxLkpvdXJuYWxFbnRyeRJUCgtMaXN0RW50cmllcxIhLmRldmpvdXJuYWwudjEuTGlzdEVudHJpZXNSZXF1ZXN0GiIuZGV2am91cm5hbC52MS5MaXN0RW50cmllc1Jlc3BvbnNlEk0KC1VwZGF0ZUVudHJ5EiEuZGV2am91cm5hbC52MS5VcGRhdGVFbnRyeVJlcXVlc3QaGy5kZXZqb3VybmFsLnYxLkpvdXJuYWxFbnRyeRJUCgtEZWxldGVFbnRyeRIhLmRldmpvdXJuYWwudjEuRGVsZXRlRW50cnlSZXF1ZXN0GiIuZGV2am91cm5hbC52MS5EZWxldGVFbnRyeVJlc3BvbnNlElgKDVNlYXJjaEVudHJpZXMSIy5kZXZqb3VybmFsLnYxLlNlYXJjaEVudHJpZXNSZXF1ZXN0GiIuZGV2am91cm5hbC52MS5MaXN0RW50cmllc1Jlc3BvbnNlQqMBChFjb20uZGV2am91cm5hbC52MUIMSm91cm5hbFByb3RvUAFaK2RldmpvdXJuYWwvcHJvdG8vZGV2am91cm5hbC92MTtkZXZqb3VybmFsdjGiAgNEWFiqAg1EZXZqb3VybmFsLlYxygINRGV2am91cm5hbFxWMeICGURldmpvdXJuYWxcVjFcR1BCTWV0YWRhdGHqAg5EZXZqb3VybmFsOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * JournalEntry represents a learning journal entry
 *
 * @generated from message devjournal.v1.JournalEntry
 */
export type JournalEntry = Message<"devjournal.v1.JournalEntry"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * excited, productive, frustrated, confused, accomplished
   *
   * @generated from field: string mood = 5;
   */
  mood: string;

  /**
   * @generated from field: repeated string tags = 6;
   */
  tags: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message devjournal.v1.JournalEntry.
 * Use `create(JournalEntrySchema)` to create a new message.
 */
export const JournalEntrySchema: GenMessage<JournalEntry> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 0);

/**
 * CreateEntryRequest is the request to create a new entry
 *
 * @generated from message devjournal.v1.CreateEntryRequest
 */
export type CreateEntryRequest = Message<"devjournal.v1.CreateEntryRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: string mood = 3;
   */
  mood: string;

  /**
   * @generated from field: repeated string tags = 4;
   */
  tags: string[];
};

/**
 * Describes the message devjournal.v1.CreateEntryRequest.
 * Use `create(CreateEntryRequestSchema)` to create a new message.
 */
export const CreateEntryRequestSchema: GenMessage<CreateEntryRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 1);

/**
 * GetEntryRequest is the request to retrieve an entry
 *
 * @generated from message devjournal.v1.GetEntryRequest
 */
export type GetEntryRequest = Message<"devjournal.v1.GetEntryRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message devjournal.v1.GetEntryRequest.
 * Use `create(GetEntryRequestSchema)` to create a new message.
 */
export const GetEntryRequestSchema: GenMessage<GetEntryRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 2);

/**
 * ListEntriesRequest is the request to list entries with pagination
 *
 * @generated from message devjournal.v1.ListEntriesRequest
 */
export type ListEntriesRequest = Message<"devjournal.v1.ListEntriesRequest"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * Optional filter by mood
   *
   * @generated from field: string mood = 3;
   */
  mood: string;
};

/**
 * Describes the message devjournal.v1.ListEntriesRequest.
 * Use `create(ListEntriesRequestSchema)` to create a new message.
 */
export const ListEntriesRequestSchema: GenMessage<ListEntriesRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 3);

/**
 * ListEntriesResponse is the response containing a list of entries
 *
 * @generated from message devjournal.v1.ListEntriesResponse
 */
export type ListEntriesResponse = Message<"devjournal.v1.ListEntriesResponse"> & {
  /**
   * @generated from field: repeated devjournal.v1.JournalEntry entries = 1;
   */
  entries: JournalEntry[];

  /**
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;
};

/**
 * Describes the message devjournal.v1.ListEntriesResponse.
 * Use `create(ListEntriesResponseSchema)` to create a new message.
 */
export const ListEntriesResponseSchema: GenMessage<ListEntriesResponse> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 4);

/**
 * UpdateEntryRequest is the request to update an entry
 *
 * @generated from message devjournal.v1.UpdateEntryRequest
 */
export type UpdateEntryRequest = Message<"devjournal.v1.UpdateEntryRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: string mood = 4;
   */
  mood: string;

  /**
   * @generated from field: repeated string tags = 5;
   */
  tags: string[];
};

/**
 * Describes the message devjournal.v1.UpdateEntryRequest.
 * Use `create(UpdateEntryRequestSchema)` to create a new message.
 */
export const UpdateEntryRequestSchema: GenMessage<UpdateEntryRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 5);

/**
 * DeleteEntryRequest is the request to delete an entry
 *
 * @generated from message devjournal.v1.DeleteEntryRequest
 */
export type DeleteEntryRequest = Message<"devjournal.v1.DeleteEntryRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message devjournal.v1.DeleteEntryRequest.
 * Use `create(DeleteEntryRequestSchema)` to create a new message.
 */
export const DeleteEntryRequestSchema: GenMessage<DeleteEntryRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 6);

/**
 * DeleteEntryResponse is the response after deleting an entry
 *
 * @generated from message devjournal.v1.DeleteEntryResponse
 */
export type DeleteEntryResponse = Message<"devjournal.v1.DeleteEntryResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message devjournal.v1.DeleteEntryResponse.
 * Use `create(DeleteEntryResponseSchema)` to create a new message.
 */
export const DeleteEntryResponseSchema: GenMessage<DeleteEntryResponse> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 7);

/**
 * SearchEntriesRequest is the request to search entries
 *
 * @generated from message devjournal.v1.SearchEntriesRequest
 */
export type SearchEntriesRequest = Message<"devjournal.v1.SearchEntriesRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 3;
   */
  offset: number;
};

/**
 * Describes the message devjournal.v1.SearchEntriesRequest.
 * Use `create(SearchEntriesRequestSchema)` to create a new message.
 */
export const SearchEntriesRequestSchema: GenMessage<SearchEntriesRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_journal, 8);

/**
 * JournalService provides CRUD operations for journal entries
 *
 * @generated from service devjournal.v1.JournalService
 */
export const JournalService: GenService<{
  /**
   * CreateEntry creates a new journal entry
   *
   * @generated from rpc devjournal.v1.JournalService.CreateEntry
   */
  createEntry: {
    methodKind: "unary";
    input: typeof CreateEntryRequestSchema;
    output: typeof JournalEntrySchema;
  },
  /**
   * GetEntry retrieves a single journal entry by ID
   *
   * @generated from rpc devjournal.v1.JournalService.GetEntry
   */
  getEntry: {
    methodKind: "unary";
    input: typeof GetEntryRequestSchema;
    output: typeof JournalEntrySchema;
  },
  /**
   * ListEntries retrieves a paginated list of journal entries
   *
   * @generated from rpc devjournal.v1.JournalService.ListEntries
   */
  listEntries: {
    methodKind: "unary";
    input: typeof ListEntriesRequestSchema;
    output: typeof ListEntriesResponseSchema;
  },
  /**
   * UpdateEntry updates an existing journal entry
   *
   * @generated from rpc devjournal.v1.JournalService.UpdateEntry
   */
  updateEntry: {
    methodKind: "unary";
    input: typeof UpdateEntryRequestSchema;
    output: typeof JournalEntrySchema;
  },
  /**
   * DeleteEntry removes a journal entry
   *
   * @generated from rpc devjournal.v1.JournalService.DeleteEntry
   */
  deleteEntry: {
    methodKind: "unary";
    input: typeof DeleteEntryRequestSchema;
    output: typeof DeleteEntryResponseSchema;
  },
  /**
   * SearchEntries searches journal entries by title or content
   *
   * @generated from rpc devjournal.v1.JournalService.SearchEntries
   */
  searchEntries: {
    methodKind: "unary";
    input: typeof SearchEntriesRequestSchema;
    output: typeof ListEntriesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_devjournal_v1_journal, 0);

