// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/progress.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file devjournal/v1/progress.proto.
 */
export const file_devjournal_v1_progress: GenFile = /*@__PURE__*/
  fileDesc("ChxkZXZqb3VybmFsL3YxL3Byb2dyZXNzLnByb3RvEg1kZXZqb3VybmFsLnYxIrcBCg1EYWlseVByb2dyZXNzEgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSKAoEZGF0ZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFQoNZW50cmllc19jb3VudBgEIAEoBRIWCg5zbmlwcGV0c19jb3VudBgFIAEoBRITCgtzdHJlYWtfZGF5cxgGIAEoBRIbChN0b3RhbF9sZWFybmluZ190aW1lGAcgASgFIsQBCg9Qcm9ncmVzc1N1bW1hcnkSFgoOY3VycmVudF9zdHJlYWsYASABKAUSFgoObG9uZ2VzdF9zdHJlYWsYAiABKAUSFQoNdG90YWxfZW50cmllcxgDIAEoBRIWCg50b3RhbF9zbmlwcGV0cxgEIAEoBRIbChN0b3RhbF9sZWFybmluZ190aW1lGAUgASgFEhkKEXRoaXNfd2Vla19lbnRyaWVzGAYgASgFEhoKEnRoaXNfbW9udGhfZW50cmllcxgHIAEoBSI+CgxQcm9ncmVzc0xpc3QSLgoIcHJvZ3Jlc3MYASADKAsyHC5kZXZqb3VybmFsLnYxLkRhaWx5UHJvZ3Jlc3MicwoOU3RyZWFrUmVzcG9uc2USFgoOY3VycmVudF9zdHJlYWsYASABKAUSFgoObG9uZ2VzdF9zdHJlYWsYAiABKAUSMQoNbGFzdF9hY3Rpdml0eRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiEwoRR2V0U3VtbWFyeVJlcXVlc3QiGQoXR2V0VG9kYXlQcm9ncmVzc1JlcXVlc3QiGgoYR2V0V2Vla2x5UHJvZ3Jlc3NSZXF1ZXN0IhsKGUdldE1vbnRobHlQcm9ncmVzc1JlcXVlc3QiEgoQR2V0U3RyZWFrUmVxdWVzdDLAAwoPUHJvZ3Jlc3NTZXJ2aWNlEk4KCkdldFN1bW1hcnkSIC5kZXZqb3VybmFsLnYxLkdldFN1bW1hcnlSZXF1ZXN0Gh4uZGV2am91cm5hbC52MS5Qcm9ncmVzc1N1bW1hcnkSWAoQR2V0VG9kYXlQcm9ncmVzcxImLmRldmpvdXJuYWwudjEuR2V0VG9kYXlQcm9ncmVzc1JlcXVlc3QaHC5kZXZqb3VybmFsLnYxLkRhaWx5UHJvZ3Jlc3MSWQoRR2V0V2Vla2x5UHJvZ3Jlc3MSJy5kZXZqb3VybmFsLnYxLkdldFdlZWtseVByb2dyZXNzUmVxdWVzdBobLmRldmpvdXJuYWwudjEuUHJvZ3Jlc3NMaXN0ElsKEkdldE1vbnRobHlQcm9ncmVzcxIoLmRldmpvdXJuYWwudjEuR2V0TW9udGhseVByb2dyZXNzUmVxdWVzdBobLmRldmpvdXJuYWwudjEuUHJvZ3Jlc3NMaXN0EksKCUdldFN0cmVhaxIfLmRldmpvdXJuYWwudjEuR2V0U3RyZWFrUmVxdWVzdBodLmRldmpvdXJuYWwudjEuU3RyZWFrUmVzcG9uc2VCpAEKEWNvbS5kZXZqb3VybmFsLnYxQg1Qcm9ncmVzc1Byb3RvUAFaK2RldmpvdXJuYWwvcHJvdG8vZGV2am91cm5hbC92MTtkZXZqb3VybmFsdjGiAgNEWFiqAg1EZXZqb3VybmFsLlYxygINRGV2am91cm5hbFxWMeICGURldmpvdXJuYWxcVjFcR1BCTWV0YWRhdGHqAg5EZXZqb3VybmFsOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * DailyProgress represents learning progress for a single day
 *
 * @generated from message devjournal.v1.DailyProgress
 */
export type DailyProgress = Message<"devjournal.v1.DailyProgress"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: google.protobuf.Timestamp date = 3;
   */
  date?: Timestamp;

  /**
   * @generated from field: int32 entries_count = 4;
   */
  entriesCount: number;

  /**
   * @generated from field: int32 snippets_count = 5;
   */
  snippetsCount: number;

  /**
   * @generated from field: int32 streak_days = 6;
   */
  streakDays: number;

  /**
   * in minutes
   *
   * @generated from field: int32 total_learning_time = 7;
   */
  totalLearningTime: number;
};

/**
 * Describes the message devjournal.v1.DailyProgress.
 * Use `create(DailyProgressSchema)` to create a new message.
 */
export const DailyProgressSchema: GenMessage<DailyProgress> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 0);

/**
 * ProgressSummary provides an overview of learning progress
 *
 * @generated from message devjournal.v1.ProgressSummary
 */
export type ProgressSummary = Message<"devjournal.v1.ProgressSummary"> & {
  /**
   * @generated from field: int32 current_streak = 1;
   */
  currentStreak: number;

  /**
   * @generated from field: int32 longest_streak = 2;
   */
  longestStreak: number;

  /**
   * @generated from field: int32 total_entries = 3;
   */
  totalEntries: number;

  /**
   * @generated from field: int32 total_snippets = 4;
   */
  totalSnippets: number;

  /**
   * in minutes
   *
   * @generated from field: int32 total_learning_time = 5;
   */
  totalLearningTime: number;

  /**
   * @generated from field: int32 this_week_entries = 6;
   */
  thisWeekEntries: number;

  /**
   * @generated from field: int32 this_month_entries = 7;
   */
  thisMonthEntries: number;
};

/**
 * Describes the message devjournal.v1.ProgressSummary.
 * Use `create(ProgressSummarySchema)` to create a new message.
 */
export const ProgressSummarySchema: GenMessage<ProgressSummary> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 1);

/**
 * ProgressList contains a list of daily progress records
 *
 * @generated from message devjournal.v1.ProgressList
 */
export type ProgressList = Message<"devjournal.v1.ProgressList"> & {
  /**
   * @generated from field: repeated devjournal.v1.DailyProgress progress = 1;
   */
  progress: DailyProgress[];
};

/**
 * Describes the message devjournal.v1.ProgressList.
 * Use `create(ProgressListSchema)` to create a new message.
 */
export const ProgressListSchema: GenMessage<ProgressList> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 2);

/**
 * StreakResponse contains streak information
 *
 * @generated from message devjournal.v1.StreakResponse
 */
export type StreakResponse = Message<"devjournal.v1.StreakResponse"> & {
  /**
   * @generated from field: int32 current_streak = 1;
   */
  currentStreak: number;

  /**
   * @generated from field: int32 longest_streak = 2;
   */
  longestStreak: number;

  /**
   * @generated from field: google.protobuf.Timestamp last_activity = 3;
   */
  lastActivity?: Timestamp;
};

/**
 * Describes the message devjournal.v1.StreakResponse.
 * Use `create(StreakResponseSchema)` to create a new message.
 */
export const StreakResponseSchema: GenMessage<StreakResponse> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 3);

/**
 * Request messages
 *
 * @generated from message devjournal.v1.GetSummaryRequest
 */
export type GetSummaryRequest = Message<"devjournal.v1.GetSummaryRequest"> & {
};

/**
 * Describes the message devjournal.v1.GetSummaryRequest.
 * Use `create(GetSummaryRequestSchema)` to create a new message.
 */
export const GetSummaryRequestSchema: GenMessage<GetSummaryRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 4);

/**
 * @generated from message devjournal.v1.GetTodayProgressRequest
 */
export type GetTodayProgressRequest = Message<"devjournal.v1.GetTodayProgressRequest"> & {
};

/**
 * Describes the message devjournal.v1.GetTodayProgressRequest.
 * Use `create(GetTodayProgressRequestSchema)` to create a new message.
 */
export const GetTodayProgressRequestSchema: GenMessage<GetTodayProgressRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 5);

/**
 * @generated from message devjournal.v1.GetWeeklyProgressRequest
 */
export type GetWeeklyProgressRequest = Message<"devjournal.v1.GetWeeklyProgressRequest"> & {
};

/**
 * Describes the message devjournal.v1.GetWeeklyProgressRequest.
 * Use `create(GetWeeklyProgressRequestSchema)` to create a new message.
 */
export const GetWeeklyProgressRequestSchema: GenMessage<GetWeeklyProgressRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 6);

/**
 * @generated from message devjournal.v1.GetMonthlyProgressRequest
 */
export type GetMonthlyProgressRequest = Message<"devjournal.v1.GetMonthlyProgressRequest"> & {
};

/**
 * Describes the message devjournal.v1.GetMonthlyProgressRequest.
 * Use `create(GetMonthlyProgressRequestSchema)` to create a new message.
 */
export const GetMonthlyProgressRequestSchema: GenMessage<GetMonthlyProgressRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 7);

/**
 * @generated from message devjournal.v1.GetStreakRequest
 */
export type GetStreakRequest = Message<"devjournal.v1.GetStreakRequest"> & {
};

/**
 * Describes the message devjournal.v1.GetStreakRequest.
 * Use `create(GetStreakRequestSchema)` to create a new message.
 */
export const GetStreakRequestSchema: GenMessage<GetStreakRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_progress, 8);

/**
 * ProgressService provides learning progress tracking
 *
 * @generated from service devjournal.v1.ProgressService
 */
export const ProgressService: GenService<{
  /**
   * GetSummary retrieves the overall progress summary
   *
   * @generated from rpc devjournal.v1.ProgressService.GetSummary
   */
  getSummary: {
    methodKind: "unary";
    input: typeof GetSummaryRequestSchema;
    output: typeof ProgressSummarySchema;
  },
  /**
   * GetTodayProgress retrieves today's progress
   *
   * @generated from rpc devjournal.v1.ProgressService.GetTodayProgress
   */
  getTodayProgress: {
    methodKind: "unary";
    input: typeof GetTodayProgressRequestSchema;
    output: typeof DailyProgressSchema;
  },
  /**
   * GetWeeklyProgress retrieves the last 7 days of progress
   *
   * @generated from rpc devjournal.v1.ProgressService.GetWeeklyProgress
   */
  getWeeklyProgress: {
    methodKind: "unary";
    input: typeof GetWeeklyProgressRequestSchema;
    output: typeof ProgressListSchema;
  },
  /**
   * GetMonthlyProgress retrieves the last 30 days of progress
   *
   * @generated from rpc devjournal.v1.ProgressService.GetMonthlyProgress
   */
  getMonthlyProgress: {
    methodKind: "unary";
    input: typeof GetMonthlyProgressRequestSchema;
    output: typeof ProgressListSchema;
  },
  /**
   * GetStreak retrieves the current learning streak
   *
   * @generated from rpc devjournal.v1.ProgressService.GetStreak
   */
  getStreak: {
    methodKind: "unary";
    input: typeof GetStreakRequestSchema;
    output: typeof StreakResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_devjournal_v1_progress, 0);

