// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/progress.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DailyProgress, GetMonthlyProgressRequest, GetStreakRequest, GetSummaryRequest, GetTodayProgressRequest, GetWeeklyProgressRequest, ProgressList, ProgressSummary, StreakResponse } from "./progress_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ProgressService provides learning progress tracking
 *
 * @generated from service devjournal.v1.ProgressService
 */
export const ProgressService = {
  typeName: "devjournal.v1.ProgressService",
  methods: {
    /**
     * GetSummary retrieves the overall progress summary
     *
     * @generated from rpc devjournal.v1.ProgressService.GetSummary
     */
    getSummary: {
      name: "GetSummary",
      I: GetSummaryRequest,
      O: ProgressSummary,
      kind: MethodKind.Unary,
    },
    /**
     * GetTodayProgress retrieves today's progress
     *
     * @generated from rpc devjournal.v1.ProgressService.GetTodayProgress
     */
    getTodayProgress: {
      name: "GetTodayProgress",
      I: GetTodayProgressRequest,
      O: DailyProgress,
      kind: MethodKind.Unary,
    },
    /**
     * GetWeeklyProgress retrieves the last 7 days of progress
     *
     * @generated from rpc devjournal.v1.ProgressService.GetWeeklyProgress
     */
    getWeeklyProgress: {
      name: "GetWeeklyProgress",
      I: GetWeeklyProgressRequest,
      O: ProgressList,
      kind: MethodKind.Unary,
    },
    /**
     * GetMonthlyProgress retrieves the last 30 days of progress
     *
     * @generated from rpc devjournal.v1.ProgressService.GetMonthlyProgress
     */
    getMonthlyProgress: {
      name: "GetMonthlyProgress",
      I: GetMonthlyProgressRequest,
      O: ProgressList,
      kind: MethodKind.Unary,
    },
    /**
     * GetStreak retrieves the current learning streak
     *
     * @generated from rpc devjournal.v1.ProgressService.GetStreak
     */
    getStreak: {
      name: "GetStreak",
      I: GetStreakRequest,
      O: StreakResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

