// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/snippet.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSnippetRequest, DeleteSnippetRequest, DeleteSnippetResponse, GetLanguageStatsRequest, GetLanguageStatsResponse, GetSnippetRequest, ListSnippetsRequest, ListSnippetsResponse, SearchSnippetsRequest, Snippet, UpdateSnippetRequest } from "./snippet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SnippetService provides CRUD operations for code snippets
 *
 * @generated from service devjournal.v1.SnippetService
 */
export const SnippetService = {
  typeName: "devjournal.v1.SnippetService",
  methods: {
    /**
     * CreateSnippet creates a new code snippet
     *
     * @generated from rpc devjournal.v1.SnippetService.CreateSnippet
     */
    createSnippet: {
      name: "CreateSnippet",
      I: CreateSnippetRequest,
      O: Snippet,
      kind: MethodKind.Unary,
    },
    /**
     * GetSnippet retrieves a single snippet by ID
     *
     * @generated from rpc devjournal.v1.SnippetService.GetSnippet
     */
    getSnippet: {
      name: "GetSnippet",
      I: GetSnippetRequest,
      O: Snippet,
      kind: MethodKind.Unary,
    },
    /**
     * ListSnippets retrieves a paginated list of snippets
     *
     * @generated from rpc devjournal.v1.SnippetService.ListSnippets
     */
    listSnippets: {
      name: "ListSnippets",
      I: ListSnippetsRequest,
      O: ListSnippetsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateSnippet updates an existing snippet
     *
     * @generated from rpc devjournal.v1.SnippetService.UpdateSnippet
     */
    updateSnippet: {
      name: "UpdateSnippet",
      I: UpdateSnippetRequest,
      O: Snippet,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteSnippet removes a snippet
     *
     * @generated from rpc devjournal.v1.SnippetService.DeleteSnippet
     */
    deleteSnippet: {
      name: "DeleteSnippet",
      I: DeleteSnippetRequest,
      O: DeleteSnippetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SearchSnippets performs full-text search on snippets
     *
     * @generated from rpc devjournal.v1.SnippetService.SearchSnippets
     */
    searchSnippets: {
      name: "SearchSnippets",
      I: SearchSnippetsRequest,
      O: ListSnippetsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLanguageStats returns snippet counts grouped by language
     *
     * @generated from rpc devjournal.v1.SnippetService.GetLanguageStats
     */
    getLanguageStats: {
      name: "GetLanguageStats",
      I: GetLanguageStatsRequest,
      O: GetLanguageStatsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

