// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/user.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file devjournal/v1/user.proto.
 */
export const file_devjournal_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChhkZXZqb3VybmFsL3YxL3VzZXIucHJvdG8SDWRldmpvdXJuYWwudjEilwEKBFVzZXISCgoCaWQYASABKAkSDQoFZW1haWwYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIkgKD1JlZ2lzdGVyUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkiLwoMTG9naW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIkAKDEF1dGhSZXNwb25zZRINCgV0b2tlbhgBIAEoCRIhCgR1c2VyGAIgASgLMhMuZGV2am91cm5hbC52MS5Vc2VyIiUKFFZhbGlkYXRlVG9rZW5SZXF1ZXN0Eg0KBXRva2VuGAEgASgJIhMKEUdldFByb2ZpbGVSZXF1ZXN0IiwKFFVwZGF0ZVByb2ZpbGVSZXF1ZXN0EhQKDGRpc3BsYXlfbmFtZRgBIAEoCTL0AgoLQXV0aFNlcnZpY2USRwoIUmVnaXN0ZXISHi5kZXZqb3VybmFsLnYxLlJlZ2lzdGVyUmVxdWVzdBobLmRldmpvdXJuYWwudjEuQXV0aFJlc3BvbnNlEkEKBUxvZ2luEhsuZGV2am91cm5hbC52MS5Mb2dpblJlcXVlc3QaGy5kZXZqb3VybmFsLnYxLkF1dGhSZXNwb25zZRJJCg1WYWxpZGF0ZVRva2VuEiMuZGV2am91cm5hbC52MS5WYWxpZGF0ZVRva2VuUmVxdWVzdBoTLmRldmpvdXJuYWwudjEuVXNlchJDCgpHZXRQcm9maWxlEiAuZGV2am91cm5hbC52MS5HZXRQcm9maWxlUmVxdWVzdBoTLmRldmpvdXJuYWwudjEuVXNlchJJCg1VcGRhdGVQcm9maWxlEiMuZGV2am91cm5hbC52MS5VcGRhdGVQcm9maWxlUmVxdWVzdBoTLmRldmpvdXJuYWwudjEuVXNlckKgAQoRY29tLmRldmpvdXJuYWwudjFCCVVzZXJQcm90b1ABWitkZXZqb3VybmFsL3Byb3RvL2RldmpvdXJuYWwvdjE7ZGV2am91cm5hbHYxogIDRFhYqgINRGV2am91cm5hbC5WMcoCDURldmpvdXJuYWxcVjHiAhlEZXZqb3VybmFsXFYxXEdQQk1ldGFkYXRh6gIORGV2am91cm5hbDo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * User represents a user in the system
 *
 * @generated from message devjournal.v1.User
 */
export type User = Message<"devjournal.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 5;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message devjournal.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 0);

/**
 * RegisterRequest is the request to register a new user
 *
 * @generated from message devjournal.v1.RegisterRequest
 */
export type RegisterRequest = Message<"devjournal.v1.RegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;
};

/**
 * Describes the message devjournal.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 1);

/**
 * LoginRequest is the request to login
 *
 * @generated from message devjournal.v1.LoginRequest
 */
export type LoginRequest = Message<"devjournal.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message devjournal.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 2);

/**
 * AuthResponse is the response containing the auth token and user
 *
 * @generated from message devjournal.v1.AuthResponse
 */
export type AuthResponse = Message<"devjournal.v1.AuthResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: devjournal.v1.User user = 2;
   */
  user?: User;
};

/**
 * Describes the message devjournal.v1.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 3);

/**
 * ValidateTokenRequest is the request to validate a token
 *
 * @generated from message devjournal.v1.ValidateTokenRequest
 */
export type ValidateTokenRequest = Message<"devjournal.v1.ValidateTokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message devjournal.v1.ValidateTokenRequest.
 * Use `create(ValidateTokenRequestSchema)` to create a new message.
 */
export const ValidateTokenRequestSchema: GenMessage<ValidateTokenRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 4);

/**
 * GetProfileRequest is the request to get the current user's profile
 *
 * @generated from message devjournal.v1.GetProfileRequest
 */
export type GetProfileRequest = Message<"devjournal.v1.GetProfileRequest"> & {
};

/**
 * Describes the message devjournal.v1.GetProfileRequest.
 * Use `create(GetProfileRequestSchema)` to create a new message.
 */
export const GetProfileRequestSchema: GenMessage<GetProfileRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 5);

/**
 * UpdateProfileRequest is the request to update the user's profile
 *
 * @generated from message devjournal.v1.UpdateProfileRequest
 */
export type UpdateProfileRequest = Message<"devjournal.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: string display_name = 1;
   */
  displayName: string;
};

/**
 * Describes the message devjournal.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest> = /*@__PURE__*/
  messageDesc(file_devjournal_v1_user, 6);

/**
 * AuthService handles user authentication
 *
 * @generated from service devjournal.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Register creates a new user account
   *
   * @generated from rpc devjournal.v1.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * Login authenticates a user and returns a token
   *
   * @generated from rpc devjournal.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * ValidateToken validates a JWT token
   *
   * @generated from rpc devjournal.v1.AuthService.ValidateToken
   */
  validateToken: {
    methodKind: "unary";
    input: typeof ValidateTokenRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * GetProfile retrieves the current user's profile
   *
   * @generated from rpc devjournal.v1.AuthService.GetProfile
   */
  getProfile: {
    methodKind: "unary";
    input: typeof GetProfileRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * UpdateProfile updates the current user's profile
   *
   * @generated from rpc devjournal.v1.AuthService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UserSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_devjournal_v1_user, 0);

