// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=js"
// @generated from file devjournal/v1/user.proto (package devjournal.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthResponse, GetProfileRequest, LoginRequest, RegisterRequest, UpdateProfileRequest, User, ValidateTokenRequest } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AuthService handles user authentication
 *
 * @generated from service devjournal.v1.AuthService
 */
export const AuthService = {
  typeName: "devjournal.v1.AuthService",
  methods: {
    /**
     * Register creates a new user account
     *
     * @generated from rpc devjournal.v1.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Login authenticates a user and returns a token
     *
     * @generated from rpc devjournal.v1.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ValidateToken validates a JWT token
     *
     * @generated from rpc devjournal.v1.AuthService.ValidateToken
     */
    validateToken: {
      name: "ValidateToken",
      I: ValidateTokenRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * GetProfile retrieves the current user's profile
     *
     * @generated from rpc devjournal.v1.AuthService.GetProfile
     */
    getProfile: {
      name: "GetProfile",
      I: GetProfileRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateProfile updates the current user's profile
     *
     * @generated from rpc devjournal.v1.AuthService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: User,
      kind: MethodKind.Unary,
    },
  }
} as const;

